import { LandingPageTemplate } from '../templates';

export const agencyTemplate: LandingPageTemplate = {
  templateId: 'agency_consulting',
  name: 'B2B Consulting & Agency Funnel',
  description: 'Sleek agency booking funnel containing embedded scheduler (Calendly), client testimonials, and B2B lead capture.',
  category: 'AGENCY',
  schema: {
    version: '1.0.0',
    pageId: 'landing_page_demo_1',
    title: 'Agency Consultation',
    slug: 'agency',
    seo: {
      title: 'Alpha Scale Marketing | Scale Your SaaS 2x',
      description: 'Elite paid traffic performance agency. We guarantee 2x pipeline growth or you pay nothing. Schedule discovery call.',
      keywords: 'agency, marketing, b2b, consulting',
    },
    theme: {
      primaryColor: '#4f46e5', // Indigo
      secondaryColor: '#0f172a',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      fontHeading: 'Inter',
      fontBody: 'Inter',
    },
    rootBlockId: 'root_block',
    blocks: {
      root_block: {
        id: 'root_block',
        type: 'container',
        name: 'Agency Root',
        parentId: null,
        children: ['agency_section', 'agency_specs_section'],
        layout: { display: { desktop: 'block' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      agency_section: {
        id: 'agency_section',
        type: 'section',
        name: 'Agency Hero',
        parentId: 'root_block',
        children: ['agency_container'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '5rem' }, paddingBottom: { desktop: '5rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      agency_container: {
        id: 'agency_container',
        type: 'container',
        name: 'Agency Container',
        parentId: 'agency_section',
        children: ['agency_title', 'agency_cta_btn'],
        layout: {},
        spacing: { paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: { textAlign: { desktop: 'center' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      agency_title: {
        id: 'agency_title',
        type: 'heading',
        name: 'Agency Title',
        parentId: 'agency_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '2rem' } },
        typography: { fontSize: { desktop: '3rem' }, fontWeight: { desktop: '800' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: 'We Double Your SaaS Product Pipeline or You Pay Nothing', level: 1 },
      },
      agency_cta_btn: {
        id: 'agency_cta_btn',
        type: 'button',
        name: 'Agency Button',
        parentId: 'agency_container',
        children: [],
        layout: {},
        spacing: {},
        typography: {},
        border: { borderRadius: { desktop: '0.375rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: 'Schedule 15-Min Discovery Call', variant: 'primary', action: { type: 'url', url: 'https://arena.ai' } },
      },
      agency_specs_section: {
        id: 'agency_specs_section',
        type: 'section',
        name: 'What We Scale',
        parentId: 'root_block',
        children: ['agency_specs_container'],
        layout: { backgroundColor: '#f1f5f9' },
        spacing: { paddingTop: { desktop: '4rem' }, paddingBottom: { desktop: '4rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      agency_specs_container: {
        id: 'agency_specs_container',
        type: 'container',
        name: 'Specs Wrapper',
        parentId: 'agency_specs_section',
        children: ['agency_specs_layout'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      agency_specs_layout: {
        id: 'agency_specs_layout',
        type: 'grid',
        name: 'Scale Specs Columns Grid',
        parentId: 'agency_specs_container',
        children: ['agency_card_1', 'agency_card_2'],
        layout: { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: '1fr 1fr' }, gap: { desktop: '2rem' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      agency_card_1: {
        id: 'agency_card_1',
        type: 'container',
        name: 'Agency Card 1',
        parentId: 'agency_specs_layout',
        children: ['agency_card_1_title', 'agency_card_1_desc'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      agency_card_1_title: {
        id: 'agency_card_1_title',
        type: 'heading',
        name: 'Card 1 Title',
        parentId: 'agency_card_1',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '🎯 Meta & TikTok Paid Ads', level: 3 },
      },
      agency_card_1_desc: {
        id: 'agency_card_1_desc',
        type: 'text',
        name: 'Card 1 description',
        parentId: 'agency_card_1',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#475569' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Stop burning ad budgets on weak funnels. We construct hyper-targeted paid traffic campaigns that convert cold traffic in seconds.</p>' },
      },
      agency_card_2: {
        id: 'agency_card_2',
        type: 'container',
        name: 'Agency Card 2',
        parentId: 'agency_specs_layout',
        children: ['agency_card_2_title', 'agency_card_2_desc'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      agency_card_2_title: {
        id: 'agency_card_2_title',
        type: 'heading',
        name: 'Card 2 Title',
        parentId: 'agency_card_2',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '⚡ Dynamic Landing Funnels', level: 3 },
      },
      agency_card_2_desc: {
        id: 'agency_card_2_desc',
        type: 'text',
        name: 'Card 2 description',
        parentId: 'agency_card_2',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#475569' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Every traffic campaign is backed by our edge-native compiled, sub-10ms landing pages, multiplying your lead generation CTR by up to 2.5x.</p>' },
      }
    }
  }
};
