import { LandingPageTemplate } from '../templates';

export const onlineCourseTemplate: LandingPageTemplate = {
  templateId: 'online_course',
  name: 'Online Course & Academy Page',
  description: 'High-converting sales funnel for digital educators with curriculum listings, video trailers, and secure checkout.',
  category: 'ONLINE_COURSE',
  schema: {
    version: '1.0.0',
    pageId: 'landing_page_demo_1',
    title: 'Course Sales Page',
    slug: 'academy',
    seo: {
      title: 'Master No-Code Architecture in 30 Days',
      description: 'Unlock enterprise-grade SaaS engineering secrets. Build robust WebOS landing page engines step-by-step.',
      keywords: 'course, academy, education, learning',
    },
    theme: {
      primaryColor: '#f59e0b', // Academy gold
      secondaryColor: '#1e293b',
      backgroundColor: '#ffffff',
      textColor: '#334155',
      fontHeading: 'Inter',
      fontBody: 'Inter',
    },
    rootBlockId: 'root_block',
    blocks: {
      root_block: {
        id: 'root_block',
        type: 'container',
        name: 'Course Root',
        parentId: null,
        children: ['course_section', 'course_specs_section'],
        layout: { display: { desktop: 'block' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      course_section: {
        id: 'course_section',
        type: 'section',
        name: 'Course Section',
        parentId: 'root_block',
        children: ['course_container'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '5rem' }, paddingBottom: { desktop: '5rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      course_container: {
        id: 'course_container',
        type: 'container',
        name: 'Course Container',
        parentId: 'course_section',
        children: ['course_heading', 'course_cta_btn'],
        layout: {},
        spacing: { paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: { textAlign: { desktop: 'center' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      course_heading: {
        id: 'course_heading',
        type: 'heading',
        name: 'Course Title',
        parentId: 'course_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '2rem' } },
        typography: { fontSize: { desktop: '3rem' }, fontWeight: { desktop: '800' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: 'Become a No-Code Full-Stack Platform Engineer', level: 1 },
      },
      course_cta_btn: {
        id: 'course_cta_btn',
        type: 'button',
        name: 'Course CTA Button',
        parentId: 'course_container',
        children: [],
        layout: {},
        spacing: {},
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: 'Secure 50% Early Bird Discount', variant: 'primary', action: { type: 'url', url: 'https://arena.ai' } },
      },
      course_specs_section: {
        id: 'course_specs_section',
        type: 'section',
        name: 'Course Curriculum',
        parentId: 'root_block',
        children: ['course_specs_container'],
        layout: { backgroundColor: '#f8fafc' },
        spacing: { paddingTop: { desktop: '4rem' }, paddingBottom: { desktop: '4rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      course_specs_container: {
        id: 'course_specs_container',
        type: 'container',
        name: 'Specs Wrapper',
        parentId: 'course_specs_section',
        children: ['course_specs_layout'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      course_specs_layout: {
        id: 'course_specs_layout',
        type: 'grid',
        name: 'Curriculum Columns Grid',
        parentId: 'course_specs_container',
        children: ['course_card_1', 'course_card_2'],
        layout: { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: '1fr 1fr' }, gap: { desktop: '2rem' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      course_card_1: {
        id: 'course_card_1',
        type: 'container',
        name: 'Curriculum Card 1',
        parentId: 'course_specs_layout',
        children: ['course_card_1_title', 'course_card_1_desc'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      course_card_1_title: {
        id: 'course_card_1_title',
        type: 'heading',
        name: 'Card 1 Title',
        parentId: 'course_card_1',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '📚 Module 1: Distributed Architectures', level: 3 },
      },
      course_card_1_desc: {
        id: 'course_card_1_desc',
        type: 'text',
        name: 'Card 1 description',
        parentId: 'course_card_1',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#475569' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Master the exact architectural blueprints of next-generation distributed SaaS systems. Redis locks, priority queues, and workers.</p>' },
      },
      course_card_2: {
        id: 'course_card_2',
        type: 'container',
        name: 'Curriculum Card 2',
        parentId: 'course_specs_layout',
        children: ['course_card_2_title', 'course_card_2_desc'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      course_card_2_title: {
        id: 'course_card_2_title',
        type: 'heading',
        name: 'Card 2 Title',
        parentId: 'course_card_2',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '💻 Module 2: High-Performance Compilers', level: 3 },
      },
      course_card_2_desc: {
        id: 'course_card_2_desc',
        type: 'text',
        name: 'Card 2 description',
        parentId: 'course_card_2',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#475569' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Build lightweight Abstract Syntax Tree (AST) compilation layers that compile visual drag components to atomic CSS classes.</p>' },
      }
    }
  }
};
