import { LandingPageTemplate } from '../templates';

export const creatorTemplate: LandingPageTemplate = {
  templateId: 'creator_bio',
  name: 'Creator Mobile-Optimized Bio-Link Page',
  description: 'Instagram/TikTok link in bio page with social links collection, profile cards, and micro-analytics tracking.',
  category: 'CREATOR_BIO',
  schema: {
    version: '1.0.0',
    pageId: 'landing_page_demo_1',
    title: 'Creator Links',
    slug: 'bio',
    seo: {
      title: 'Alex Rivers | Creator Portal',
      description: 'Elite creator tech reviews. Check out my latest YouTube videos, gear checklists, and exclusive newsletter.',
      keywords: 'creator, bio, links, tiktok',
    },
    theme: {
      primaryColor: '#ec4899', // Pink
      secondaryColor: '#f43f5e',
      backgroundColor: '#090d16', // Slate space dark
      textColor: '#f1f5f9',
      fontHeading: 'Inter',
      fontBody: 'Inter',
    },
    rootBlockId: 'root_block',
    blocks: {
      root_block: {
        id: 'root_block',
        type: 'container',
        name: 'Creator Root',
        parentId: null,
        children: ['bio_section'],
        layout: { display: { desktop: 'block' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      bio_section: {
        id: 'bio_section',
        type: 'section',
        name: 'Bio Main Section',
        parentId: 'root_block',
        children: ['bio_container'],
        layout: { backgroundColor: '#090d16' },
        spacing: { paddingTop: { desktop: '3rem' }, paddingBottom: { desktop: '3rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      bio_container: {
        id: 'bio_container',
        type: 'container',
        name: 'Bio Container',
        parentId: 'bio_section',
        children: ['bio_title', 'bio_link_1', 'bio_link_2'],
        layout: {},
        spacing: { paddingLeft: { desktop: '1.5rem' }, paddingRight: { desktop: '1.5rem' } },
        typography: { textAlign: { desktop: 'center' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      bio_title: {
        id: 'bio_title',
        type: 'heading',
        name: 'Creator Bio Title',
        parentId: 'bio_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '2rem' } },
        typography: { fontSize: { desktop: '1.5rem' }, fontWeight: { desktop: '700' }, color: '#f1f5f9' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '@AlexRivers | Creator Space', level: 1 },
      },
      bio_link_1: {
        id: 'bio_link_1',
        type: 'button',
        name: 'YouTube Channel Link',
        parentId: 'bio_container',
        children: [],
        layout: { width: { desktop: '100%' } },
        spacing: { paddingTop: { desktop: '1rem' }, paddingBottom: { desktop: '1rem' }, marginBottom: { desktop: '1rem' } },
        typography: { fontWeight: { desktop: '600' } },
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: '🎥 Subscribe to my YouTube Channel', variant: 'primary', action: { type: 'url', url: 'https://arena.ai' } },
      },
      bio_link_2: {
        id: 'bio_link_2',
        type: 'button',
        name: 'Latest Tech Checklist Link',
        parentId: 'bio_container',
        children: [],
        layout: { width: { desktop: '100%' } },
        spacing: { paddingTop: { desktop: '1rem' }, paddingBottom: { desktop: '1rem' } },
        typography: { fontWeight: { desktop: '600' } },
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: '⚙️ My 2026 Tech Gear Setup Checklist', variant: 'primary', action: { type: 'url', url: 'https://arena.ai' } },
      }
    }
  }
};
