import { LandingPageTemplate } from '../templates';

export const dropshippingLanderTemplate: LandingPageTemplate = {
  templateId: 'dropshipping_lander',
  name: 'E-commerce Single-Product Funnel',
  description: 'An premium, high-conversion product landing funnel optimized for single products with countdown timers, customer trust proof, and glowing CTA purchase forms.',
  category: 'DROPSHIPPING',
  schema: {
    version: '1.0.0',
    pageId: 'landing_page_demo_1',
    title: 'Product Funnel Home',
    slug: 'product',
    seo: {
      title: 'Portable Blender Elite | Instant Blend Anywhere',
      description: 'Get your Portable Blender Elite today with 50% discount and global free delivery. High quality, bpa-free, rapid usb charging.',
      keywords: 'blender, product, sale, dropshipping',
    },
    theme: {
      primaryColor: '#ef4444',
      secondaryColor: '#1e293b',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
      fontHeading: 'Inter',
      fontBody: 'Inter',
    },
    rootBlockId: 'root_block',
    blocks: {
      root_block: {
        id: 'root_block',
        type: 'container',
        name: 'Product Page Root',
        parentId: null,
        children: ['product_hero_section'],
        layout: { display: { desktop: 'block' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      product_hero_section: {
        id: 'product_hero_section',
        type: 'section',
        name: 'Product Hero Layout',
        parentId: 'root_block',
        children: ['product_container'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '5rem', mobile: '2.5rem' }, paddingBottom: { desktop: '5rem', mobile: '2.5rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      product_container: {
        id: 'product_container',
        type: 'container',
        name: 'Product Split Container',
        parentId: 'product_hero_section',
        children: ['product_split_grid'],
        layout: {},
        spacing: { paddingLeft: { desktop: '1.5rem' }, paddingRight: { desktop: '1.5rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      product_split_grid: {
        id: 'product_split_grid',
        type: 'grid',
        name: '2-Column Product Grid',
        parentId: 'product_container',
        children: ['product_media_column', 'product_checkout_column'],
        layout: { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: '1fr 1.1fr' }, gap: { desktop: '4rem' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      product_media_column: {
        id: 'product_media_column',
        type: 'container',
        name: 'Media Gallery Column',
        parentId: 'product_split_grid',
        children: ['product_main_image', 'product_trust_badges'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      product_main_image: {
        id: 'product_main_image',
        type: 'image',
        name: 'Main Product Photo',
        parentId: 'product_media_column',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '1rem' } },
        shadow: { boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.15)' },
        animation: { type: 'fade-in', duration: 1000 },
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { src: 'https://images.unsplash.com/photo-1578643463396-0997cb5328c1?w=800', alt: 'Premium Blender product graphic' },
      },
      product_trust_badges: {
        id: 'product_trust_badges',
        type: 'text',
        name: 'Trust Badges Copy',
        parentId: 'product_media_column',
        children: [],
        layout: {},
        spacing: {},
        typography: { textAlign: { desktop: 'center' }, color: '#059669', fontSize: { desktop: '0.95rem' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p><strong>🛡️ 30-Day Money Back Guarantee | ✈️ Free Worldwide Fast Delivery</strong></p>' },
      },
      product_checkout_column: {
        id: 'product_checkout_column',
        type: 'container',
        name: 'Checkout Funnel Details',
        parentId: 'product_split_grid',
        children: ['product_badge', 'product_title', 'product_price', 'product_form'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      product_badge: {
        id: 'product_badge',
        type: 'text',
        name: 'Hot Sale Tag',
        parentId: 'product_checkout_column',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.75rem' } },
        typography: { color: '#ef4444', fontWeight: { desktop: '800' }, fontSize: { desktop: '0.875rem' }, letterSpacing: { desktop: '0.05em' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<span>🔥 SELLING FAST - 50% LIMITED DISCOUNT ENDS TODAY</span>' },
      },
      product_title: {
        id: 'product_title',
        type: 'heading',
        name: 'Product Headline Title',
        parentId: 'product_checkout_column',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '1.25rem' } },
        typography: { fontSize: { desktop: '2.75rem', mobile: '2rem' }, fontWeight: { desktop: '900' }, letterSpacing: { desktop: '-0.03em' }, lineHeight: { desktop: '1.15' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: 'Portable Blender Elite v2', level: 1 },
      },
      product_price: {
        id: 'product_price',
        type: 'text',
        name: 'Price Tag Label',
        parentId: 'product_checkout_column',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '2.5rem' } },
        typography: { fontSize: { desktop: '2rem' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p><span style="text-decoration:line-through; color:#94a3b8; margin-right:12px;">$79.99</span><strong style="color:#ef4444; font-size: 2.25rem;">$39.99</strong></p>' },
      },
      product_form: {
        id: 'product_form',
        type: 'form',
        name: 'One-Click Checkout Form',
        parentId: 'product_checkout_column',
        children: ['product_cta_checkout_btn'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { submitMethod: 'SUPABASE', successMessage: '🎉 Success! Your order is secured. We will contact you on WhatsApp shortly.' },
      },
      product_cta_checkout_btn: {
        id: 'product_cta_checkout_btn',
        type: 'button',
        name: 'Order CTA button',
        parentId: 'product_form',
        children: [],
        layout: { width: { desktop: '100%' }, backgroundColor: '#ef4444' },
        spacing: { paddingTop: { desktop: '1.25rem' }, paddingBottom: { desktop: '1.25rem' } },
        typography: { color: '#ffffff', fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '800' } },
        border: { borderRadius: { desktop: '0.75rem' } },
        shadow: { boxShadow: '0 10px 15px -3px rgba(239, 68, 68, 0.4)' },
        animation: { type: 'pulse', duration: 1500, infinite: true },
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: '🎯 BUY NOW & SAVE 50%', variant: 'primary', action: { type: 'url', url: 'https://arena.ai' } },
      }
    }
  }
};
