import { LandingPageTemplate } from '../templates';

export const fitnessTemplate: LandingPageTemplate = {
  templateId: 'fitness_trainer',
  name: 'Fitness & Personal Coaching Page',
  description: 'Transformational coaching landing page with package selectors, diet plans, and client results gallery.',
  category: 'FITNESS',
  schema: {
    version: '1.0.0',
    pageId: 'landing_page_demo_1',
    title: 'Fitness Transformation',
    slug: 'coaching',
    seo: {
      title: '30-Day Lean Muscle Transformation | Coach Elite',
      description: 'Personalized training, strict s-curve diet blueprints, and 1-on-1 daily accountability. Get lean now.',
      keywords: 'fitness, training, coach, workout',
    },
    theme: {
      primaryColor: '#16a34a', // Vitality green
      secondaryColor: '#020617',
      backgroundColor: '#ffffff',
      textColor: '#0f172a',
      fontHeading: 'Inter',
      fontBody: 'Inter',
    },
    rootBlockId: 'root_block',
    blocks: {
      root_block: {
        id: 'root_block',
        type: 'container',
        name: 'Fitness Root',
        parentId: null,
        children: ['fitness_section', 'fitness_specs_section'],
        layout: { display: { desktop: 'block' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      fitness_section: {
        id: 'fitness_section',
        type: 'section',
        name: 'Fitness Section',
        parentId: 'root_block',
        children: ['fitness_container'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '5rem' }, paddingBottom: { desktop: '5rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      fitness_container: {
        id: 'fitness_container',
        type: 'container',
        name: 'Fitness Container',
        parentId: 'fitness_section',
        children: ['fitness_title', 'fitness_cta_btn'],
        layout: {},
        spacing: { paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: { textAlign: { desktop: 'center' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      fitness_title: {
        id: 'fitness_title',
        type: 'heading',
        name: 'Fitness Title',
        parentId: 'fitness_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '2rem' } },
        typography: { fontSize: { desktop: '3rem' }, fontWeight: { desktop: '900' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: 'Elite 1-on-1 Daily Accountability Muscle Program', level: 1 },
      },
      fitness_cta_btn: {
        id: 'fitness_cta_btn',
        type: 'button',
        name: 'Fitness Button',
        parentId: 'fitness_container',
        children: [],
        layout: {},
        spacing: {},
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: 'Apply For Coaching Program', variant: 'primary', action: { type: 'url', url: 'https://arena.ai' } },
      },
      fitness_specs_section: {
        id: 'fitness_specs_section',
        type: 'section',
        name: 'What You Get Section',
        parentId: 'root_block',
        children: ['fitness_specs_container'],
        layout: { backgroundColor: '#f0fdf4' },
        spacing: { paddingTop: { desktop: '4rem' }, paddingBottom: { desktop: '4rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      fitness_specs_container: {
        id: 'fitness_specs_container',
        type: 'container',
        name: 'Specs Box',
        parentId: 'fitness_specs_section',
        children: ['fitness_specs_layout'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      fitness_specs_layout: {
        id: 'fitness_specs_layout',
        type: 'grid',
        name: 'Specs Columns Grid',
        parentId: 'fitness_specs_container',
        children: ['fitness_card_1', 'fitness_card_2'],
        layout: { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: '1fr 1fr' }, gap: { desktop: '2rem' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      fitness_card_1: {
        id: 'fitness_card_1',
        type: 'container',
        name: 'Fitness Card 1',
        parentId: 'fitness_specs_layout',
        children: ['fitness_card_1_title', 'fitness_card_1_desc'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      fitness_card_1_title: {
        id: 'fitness_card_1_title',
        type: 'heading',
        name: 'Card 1 Title',
        parentId: 'fitness_card_1',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '🥦 Custom 7-Day Diet Blueprints', level: 3 },
      },
      fitness_card_1_desc: {
        id: 'fitness_card_1_desc',
        type: 'text',
        name: 'Card 1 description',
        parentId: 'fitness_card_1',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#475569' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Zero starvation. Calculated s-curve caloric intake matching your daily schedules, packed with clean, tasty high-protein meals.</p>' },
      },
      fitness_card_2: {
        id: 'fitness_card_2',
        type: 'container',
        name: 'Fitness Card 2',
        parentId: 'fitness_specs_layout',
        children: ['fitness_card_2_title', 'fitness_card_2_desc'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      fitness_card_2_title: {
        id: 'fitness_card_2_title',
        type: 'heading',
        name: 'Card 2 Title',
        parentId: 'fitness_card_2',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '📱 1-on-1 WhatsApp Accountability', level: 3 },
      },
      fitness_card_2_desc: {
        id: 'fitness_card_2_desc',
        type: 'text',
        name: 'Card 2 description',
        parentId: 'fitness_card_2',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#475569' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Direct, daily checks with Coach Elite. Submit progress photos, log sleep data, and adjust training programs on the fly.</p>' },
      }
    }
  }
};
