import { LandingPageTemplate } from '../templates';

export const localServicesTemplate: LandingPageTemplate = {
  templateId: 'local_services',
  name: 'Local Services & Repair Trades Landing Page',
  description: 'Highly localized plumber, electrician, and handyman lead generator with service catalogs and 24/7 call buttons.',
  category: 'LOCAL_SERVICES',
  schema: {
    version: '1.0.0',
    pageId: 'landing_page_demo_1',
    title: 'Plumbing Services',
    slug: 'plumber',
    seo: {
      title: 'Emergency Plumbing Repair Chicago | Elite Plumbers',
      description: 'Elite Chicago Plumbers. Certified, insured, and 24/7 emergency service. Burst pipes, clogs, and water heater repairs.',
      keywords: 'plumbing, emergency, repair, local',
    },
    theme: {
      primaryColor: '#1d4ed8', // Trustworthy dark blue
      secondaryColor: '#f97316', // Emergency orange
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
      fontHeading: 'Inter',
      fontBody: 'Inter',
    },
    rootBlockId: 'root_block',
    blocks: {
      root_block: {
        id: 'root_block',
        type: 'container',
        name: 'Local Services Root',
        parentId: null,
        children: ['local_section', 'local_grid_section'],
        layout: { display: { desktop: 'block' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      local_section: {
        id: 'local_section',
        type: 'section',
        name: 'Local Hero',
        parentId: 'root_block',
        children: ['local_container'],
        layout: { backgroundColor: '#f8fafc' },
        spacing: { paddingTop: { desktop: '4rem' }, paddingBottom: { desktop: '4rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      local_container: {
        id: 'local_container',
        type: 'container',
        name: 'Local Container',
        parentId: 'local_section',
        children: ['local_title', 'local_cta_btn'],
        layout: {},
        spacing: { paddingLeft: { desktop: '1.5rem' }, paddingRight: { desktop: '1.5rem' } },
        typography: { textAlign: { desktop: 'center' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      local_title: {
        id: 'local_title',
        type: 'heading',
        name: 'Local Service Title',
        parentId: 'local_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '2rem' } },
        typography: { fontSize: { desktop: '2.5rem' }, fontWeight: { desktop: '800' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '24/7 Professional Chicago Emergency Plumbers', level: 1 },
      },
      local_cta_btn: {
        id: 'local_cta_btn',
        type: 'button',
        name: 'Emergency Call Button',
        parentId: 'local_container',
        children: [],
        layout: {},
        spacing: {},
        typography: {},
        border: { borderRadius: { desktop: '0.375rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: '📞 Call Now (800) 555-0199', variant: 'primary', action: { type: 'url', url: 'tel:+18005550199' } },
      },
      local_grid_section: {
        id: 'local_grid_section',
        type: 'section',
        name: 'Service List Section',
        parentId: 'root_block',
        children: ['local_grid_container'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '4rem' }, paddingBottom: { desktop: '4rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      local_grid_container: {
        id: 'local_grid_container',
        type: 'container',
        name: 'Grid Wrapper',
        parentId: 'local_grid_section',
        children: ['local_grid_layout'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      local_grid_layout: {
        id: 'local_grid_layout',
        type: 'grid',
        name: 'Service Columns Grid',
        parentId: 'local_grid_container',
        children: ['local_card_1', 'local_card_2'],
        layout: { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: '1fr 1fr' }, gap: { desktop: '2rem' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      local_card_1: {
        id: 'local_card_1',
        type: 'container',
        name: 'Local Card 1',
        parentId: 'local_grid_layout',
        children: ['local_card_1_title', 'local_card_1_desc'],
        layout: { backgroundColor: '#eff6ff' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      local_card_1_title: {
        id: 'local_card_1_title',
        type: 'heading',
        name: 'Card 1 Title',
        parentId: 'local_card_1',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '🛠️ Drain Clog Cleaning', level: 3 },
      },
      local_card_1_desc: {
        id: 'local_card_1_desc',
        type: 'text',
        name: 'Card 1 description',
        parentId: 'local_card_1',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#1e293b' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Instant, painless clearing of blocked bathroom drains, kitchen sewers, and industrial pipes using certified micro-boring technology.</p>' },
      },
      local_card_2: {
        id: 'local_card_2',
        type: 'container',
        name: 'Local Card 2',
        parentId: 'local_grid_layout',
        children: ['local_card_2_title', 'local_card_2_desc'],
        layout: { backgroundColor: '#eff6ff' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      local_card_2_title: {
        id: 'local_card_2_title',
        type: 'heading',
        name: 'Card 2 Title',
        parentId: 'local_card_2',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '🔥 Boiler & Water Heater Repair', level: 3 },
      },
      local_card_2_desc: {
        id: 'local_card_2_desc',
        type: 'text',
        name: 'Card 2 description',
        parentId: 'local_card_2',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#1e293b' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Certified technicians available 24/7 to repair leaky boilers, install dynamic thermostats, and restore hot water instantly.</p>' },
      }
    }
  }
};
