import { LandingPageTemplate } from '../templates';

export const medicalTemplate: LandingPageTemplate = {
  templateId: 'medical_clinic',
  name: 'Medical & Dental Booking Page',
  description: 'Highly professional medical clinic landing page with doctor profiles, localized maps, and secure consultation booking forms.',
  category: 'MEDICAL',
  schema: {
    version: '1.0.0',
    pageId: 'landing_page_demo_1',
    title: 'Clinic Appointment',
    slug: 'dental',
    seo: {
      title: 'Elite Dental Clinic | Smile Transformation',
      description: 'Book your complimentary diagnostic checkup at Elite Dental. Modern implants, painless treatments, and personalized plans.',
      keywords: 'dentistry, clinic, implants, booking',
    },
    theme: {
      primaryColor: '#0ea5e9', // Medical sky blue
      secondaryColor: '#0f172a',
      backgroundColor: '#ffffff',
      textColor: '#334155',
      fontHeading: 'Inter',
      fontBody: 'Inter',
    },
    rootBlockId: 'root_block',
    blocks: {
      root_block: {
        id: 'root_block',
        type: 'container',
        name: 'Medical Root',
        parentId: null,
        children: ['med_section', 'med_specs_section'],
        layout: { display: { desktop: 'block' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      med_section: {
        id: 'med_section',
        type: 'section',
        name: 'Medical Section',
        parentId: 'root_block',
        children: ['med_container'],
        layout: { backgroundColor: '#f0f9ff' },
        spacing: { paddingTop: { desktop: '4rem' }, paddingBottom: { desktop: '4rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      med_container: {
        id: 'med_container',
        type: 'container',
        name: 'Medical Container',
        parentId: 'med_section',
        children: ['med_title', 'med_cta_btn'],
        layout: {},
        spacing: { paddingLeft: { desktop: '1.5rem' }, paddingRight: { desktop: '1.5rem' } },
        typography: { textAlign: { desktop: 'center' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      med_title: {
        id: 'med_title',
        type: 'heading',
        name: 'Medical Title',
        parentId: 'med_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '2rem' } },
        typography: { fontSize: { desktop: '2.5rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: 'Painless Smile Dental Transformation', level: 1 },
      },
      med_cta_btn: {
        id: 'med_cta_btn',
        type: 'button',
        name: 'Medical CTA Button',
        parentId: 'med_container',
        children: [],
        layout: {},
        spacing: {},
        typography: {},
        border: { borderRadius: { desktop: '9999px' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: 'Book Diagnostic Checkup Free', variant: 'primary', action: { type: 'url', url: 'https://arena.ai' } },
      },
      med_specs_section: {
        id: 'med_specs_section',
        type: 'section',
        name: 'Clinic Specifications',
        parentId: 'root_block',
        children: ['med_specs_container'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '4rem' }, paddingBottom: { desktop: '4rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      med_specs_container: {
        id: 'med_specs_container',
        type: 'container',
        name: 'Specs Wrapper',
        parentId: 'med_specs_section',
        children: ['med_specs_layout'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      med_specs_layout: {
        id: 'med_specs_layout',
        type: 'grid',
        name: 'Clinicians Specs Grid',
        parentId: 'med_specs_container',
        children: ['med_card_1', 'med_card_2'],
        layout: { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: '1fr 1fr' }, gap: { desktop: '2rem' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      med_card_1: {
        id: 'med_card_1',
        type: 'container',
        name: 'Med Card 1',
        parentId: 'med_specs_layout',
        children: ['med_card_1_title', 'med_card_1_desc'],
        layout: { backgroundColor: '#f0fdf4' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      med_card_1_title: {
        id: 'med_card_1_title',
        type: 'heading',
        name: 'Card 1 Title',
        parentId: 'med_card_1',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '🩺 Painless Treatment Protocol', level: 3 },
      },
      med_card_1_desc: {
        id: 'med_card_1_desc',
        type: 'text',
        name: 'Card 1 description',
        parentId: 'med_card_1',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#1e293b' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Our dentists leverage cutting edge localized anesthesia techniques to deliver completely pain-free, comfortable smile treatments.</p>' },
      },
      med_card_2: {
        id: 'med_card_2',
        type: 'container',
        name: 'Med Card 2',
        parentId: 'med_specs_layout',
        children: ['med_card_2_title', 'med_card_2_desc'],
        layout: { backgroundColor: '#f0fdf4' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      med_card_2_title: {
        id: 'med_card_2_title',
        type: 'heading',
        name: 'Card 2 Title',
        parentId: 'med_card_2',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '🦷 Certified Materials Only', level: 3 },
      },
      med_card_2_desc: {
        id: 'med_card_2_desc',
        type: 'text',
        name: 'Card 2 description',
        parentId: 'med_card_2',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#1e293b' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Every implant, crown, and diagnostic resin utilizes 100% FDA approved, high-durability biocompatible materials built to last a lifetime.</p>' },
      }
    }
  }
};
