import type { LandingPageTemplate } from '../templates';
import type { BaseBlock, BlockType, PageBuilderSchema } from '../../../types/builder';

type TemplateCategory = LandingPageTemplate['category'];

export type ProfessionalTemplateSpec = {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  audience: string;
  headline: string;
  subheadline: string;
  cta: string;
  accent: string;
  accent2: string;
  bg: string;
  surface: string;
  text: string;
  muted: string;
  proof: string[];
  benefits: Array<{ title: string; body: string }>;
  process: string[];
};

const visibility = { showOnDesktop: true, showOnTablet: true, showOnMobile: true };

const block = (
  id: string,
  type: BlockType,
  name: string,
  parentId: string | null,
  children: string[] = [],
  layout: BaseBlock['layout'] = {},
  spacing: BaseBlock['spacing'] = {},
  typography: BaseBlock['typography'] = {},
  border: BaseBlock['border'] = {},
  shadow: BaseBlock['shadow'] = {},
  animation: BaseBlock['animation'] = {},
  props: BaseBlock['props'] = {}
): BaseBlock => ({
  id,
  type,
  name,
  parentId,
  children,
  layout,
  spacing,
  typography,
  border,
  shadow,
  animation,
  visibility,
  props,
});

const richText = (content: string) => `<p>${content}</p>`;

export function createProfessionalTemplate(spec: ProfessionalTemplateSpec): LandingPageTemplate {
  const p = spec.id.replace(/[^a-z0-9_]/g, '_');
  const schema: PageBuilderSchema = {
    version: '1.0.0',
    pageId: `${p}_page`,
    title: spec.name,
    slug: 'home',
    seo: {
      title: spec.headline,
      description: spec.description,
      keywords: `${spec.audience}, landing page, conversion, vortic, ${spec.category.toLowerCase()}`,
    },
    theme: {
      primaryColor: spec.accent,
      secondaryColor: spec.accent2,
      backgroundColor: spec.bg,
      textColor: spec.text,
      fontHeading: 'Inter',
      fontBody: 'Inter',
    },
    rootBlockId: `${p}_root`,
    blocks: {
      [`${p}_root`]: block(
        `${p}_root`,
        'container',
        'Premium page root',
        null,
        [`${p}_hero`, `${p}_proof`, `${p}_benefits`, `${p}_process`, `${p}_lead`],
        { display: { desktop: 'block' }, width: { desktop: '100%' }, backgroundColor: spec.bg },
      ),
      [`${p}_hero`]: block(
        `${p}_hero`,
        'section',
        'Cinematic conversion hero',
        `${p}_root`,
        [`${p}_hero_wrap`],
        { backgroundColor: spec.bg },
        { paddingTop: { desktop: '7rem', mobile: '4rem' }, paddingBottom: { desktop: '5rem', mobile: '3rem' } },
      ),
      [`${p}_hero_wrap`]: block(
        `${p}_hero_wrap`,
        'container',
        'Hero content wrapper',
        `${p}_hero`,
        [`${p}_eyebrow`, `${p}_headline`, `${p}_subheadline`, `${p}_cta`, `${p}_hero_note`],
        { display: { desktop: 'flex' }, flexDirection: { desktop: 'column' }, alignItems: { desktop: 'center' }, maxWidth: { desktop: '980px' } },
        { paddingLeft: { desktop: '1.5rem' }, paddingRight: { desktop: '1.5rem' } },
        { textAlign: { desktop: 'center' } },
      ),
      [`${p}_eyebrow`]: block(
        `${p}_eyebrow`,
        'text',
        'Trust eyebrow',
        `${p}_hero_wrap`,
        [],
        {},
        { marginBottom: { desktop: '1.25rem' } },
        { color: spec.accent, fontSize: { desktop: '0.78rem' }, fontWeight: { desktop: '900' }, letterSpacing: { desktop: '0.16em' }, textTransform: 'uppercase' },
        {},
        {},
        { type: 'fade-in', duration: 500 },
        { htmlContent: richText(`Built for ${spec.audience}`) },
      ),
      [`${p}_headline`]: block(
        `${p}_headline`,
        'heading',
        'Hero headline',
        `${p}_hero_wrap`,
        [],
        {},
        { marginBottom: { desktop: '1.5rem' } },
        { color: spec.text, fontSize: { desktop: '4.4rem', tablet: '3.4rem', mobile: '2.35rem' }, fontWeight: { desktop: '900' }, lineHeight: { desktop: '1.02' }, letterSpacing: { desktop: '-0.055em' } },
        {},
        { textShadow: `0 20px 60px ${spec.accent}33` },
        { type: 'slide-up', duration: 750 },
        { text: spec.headline, level: 1 },
      ),
      [`${p}_subheadline`]: block(
        `${p}_subheadline`,
        'text',
        'Hero subheadline',
        `${p}_hero_wrap`,
        [],
        { maxWidth: { desktop: '720px' } },
        { marginBottom: { desktop: '2rem' } },
        { color: spec.muted, fontSize: { desktop: '1.18rem', mobile: '1rem' }, lineHeight: { desktop: '1.75' } },
        {},
        {},
        { type: 'fade-in', duration: 900 },
        { htmlContent: richText(spec.subheadline) },
      ),
      [`${p}_cta`]: block(
        `${p}_cta`,
        'button',
        'Primary conversion CTA',
        `${p}_hero_wrap`,
        [],
        {},
        { paddingTop: { desktop: '1rem' }, paddingBottom: { desktop: '1rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' }, marginBottom: { desktop: '1.2rem' } },
        { color: '#ffffff', fontSize: { desktop: '1rem' }, fontWeight: { desktop: '900' } },
        { borderRadius: { desktop: '999px' } },
        { boxShadow: `0 18px 45px ${spec.accent}55` },
        { type: 'pulse', duration: 2400, infinite: true },
        { label: spec.cta, variant: 'primary', action: { type: 'url', url: '/editor', target: '_self' } },
      ),
      [`${p}_hero_note`]: block(
        `${p}_hero_note`,
        'text',
        'Risk reversal note',
        `${p}_hero_wrap`,
        [],
        {},
        {},
        { color: spec.muted, fontSize: { desktop: '0.82rem' } },
        {},
        {},
        {},
        { htmlContent: richText('No-code editing · Edge-compiled pages · Secure forms · Launch-ready in minutes') },
      ),
      [`${p}_proof`]: block(
        `${p}_proof`,
        'section',
        'Proof bar',
        `${p}_root`,
        [`${p}_proof_grid`],
        { backgroundColor: spec.surface },
        { paddingTop: { desktop: '1.6rem' }, paddingBottom: { desktop: '1.6rem' }, paddingLeft: { desktop: '1.5rem' }, paddingRight: { desktop: '1.5rem' } },
      ),
      [`${p}_proof_grid`]: block(
        `${p}_proof_grid`,
        'grid',
        'Three metric proof grid',
        `${p}_proof`,
        spec.proof.map((_, index) => `${p}_proof_${index + 1}`),
        { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: 'repeat(3, minmax(0, 1fr))' }, gap: { desktop: '1rem' }, maxWidth: { desktop: '1100px' } },
        { marginLeft: { desktop: 'auto' }, marginRight: { desktop: 'auto' } },
      ),
      ...Object.fromEntries(spec.proof.map((item, index) => [
        `${p}_proof_${index + 1}`,
        block(
          `${p}_proof_${index + 1}`,
          'text',
          `Proof point ${index + 1}`,
          `${p}_proof_grid`,
          [],
          { backgroundColor: `${spec.bg}` },
          { paddingTop: { desktop: '1rem' }, paddingBottom: { desktop: '1rem' }, paddingLeft: { desktop: '1rem' }, paddingRight: { desktop: '1rem' }, marginBottom: { desktop: '0', mobile: '0.75rem' } },
          { color: spec.text, textAlign: { desktop: 'center' }, fontWeight: { desktop: '800' }, fontSize: { desktop: '0.92rem' } },
          { borderRadius: { desktop: '1rem' }, borderStyle: 'solid', borderWidth: { desktop: '1px' }, borderColor: `${spec.accent}33` },
          {},
          {},
          { htmlContent: richText(item) },
        )
      ])),
      [`${p}_benefits`]: block(
        `${p}_benefits`,
        'section',
        'Benefits section',
        `${p}_root`,
        [`${p}_benefits_wrap`],
        { backgroundColor: spec.bg },
        { paddingTop: { desktop: '5.5rem', mobile: '3rem' }, paddingBottom: { desktop: '5.5rem', mobile: '3rem' } },
      ),
      [`${p}_benefits_wrap`]: block(
        `${p}_benefits_wrap`,
        'container',
        'Benefits wrapper',
        `${p}_benefits`,
        [`${p}_benefits_title`, `${p}_benefits_grid`],
        { maxWidth: { desktop: '1120px' } },
        { paddingLeft: { desktop: '1.5rem' }, paddingRight: { desktop: '1.5rem' } },
      ),
      [`${p}_benefits_title`]: block(
        `${p}_benefits_title`,
        'heading',
        'Benefits title',
        `${p}_benefits_wrap`,
        [],
        {},
        { marginBottom: { desktop: '2.5rem' } },
        { color: spec.text, fontSize: { desktop: '2.6rem', mobile: '1.9rem' }, fontWeight: { desktop: '900' }, textAlign: { desktop: 'center' }, letterSpacing: { desktop: '-0.035em' } },
        {},
        {},
        {},
        { text: 'Everything needed to convert visitors into customers', level: 2 },
      ),
      [`${p}_benefits_grid`]: block(
        `${p}_benefits_grid`,
        'grid',
        'Benefits card grid',
        `${p}_benefits_wrap`,
        spec.benefits.map((_, index) => `${p}_benefit_${index + 1}`),
        { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: 'repeat(3, minmax(0, 1fr))' }, gap: { desktop: '1.4rem' } },
      ),
      ...Object.fromEntries(spec.benefits.map((benefit, index) => [
        `${p}_benefit_${index + 1}`,
        block(
          `${p}_benefit_${index + 1}`,
          'container',
          `Benefit card ${index + 1}`,
          `${p}_benefits_grid`,
          [`${p}_benefit_${index + 1}_title`, `${p}_benefit_${index + 1}_body`],
          { backgroundColor: spec.surface },
          { paddingTop: { desktop: '1.6rem' }, paddingBottom: { desktop: '1.6rem' }, paddingLeft: { desktop: '1.4rem' }, paddingRight: { desktop: '1.4rem' }, marginBottom: { desktop: '0', mobile: '1rem' } },
          {},
          { borderRadius: { desktop: '1.35rem' }, borderStyle: 'solid', borderWidth: { desktop: '1px' }, borderColor: `${spec.accent}22` },
          { boxShadow: '0 18px 50px rgba(0,0,0,0.18)' },
        )
      ])),
      ...Object.fromEntries(spec.benefits.flatMap((benefit, index) => ([
        [`${p}_benefit_${index + 1}_title`, block(
          `${p}_benefit_${index + 1}_title`,
          'heading',
          `Benefit ${index + 1} title`,
          `${p}_benefit_${index + 1}`,
          [],
          {},
          { marginBottom: { desktop: '0.75rem' } },
          { color: spec.text, fontSize: { desktop: '1.18rem' }, fontWeight: { desktop: '900' } },
          {},
          {},
          {},
          { text: benefit.title, level: 3 },
        )],
        [`${p}_benefit_${index + 1}_body`, block(
          `${p}_benefit_${index + 1}_body`,
          'text',
          `Benefit ${index + 1} body`,
          `${p}_benefit_${index + 1}`,
          [],
          {},
          {},
          { color: spec.muted, lineHeight: { desktop: '1.7' }, fontSize: { desktop: '0.94rem' } },
          {},
          {},
          {},
          { htmlContent: richText(benefit.body) },
        )]
      ]))),
      [`${p}_process`]: block(
        `${p}_process`,
        'section',
        'Process section',
        `${p}_root`,
        [`${p}_process_wrap`],
        { backgroundColor: spec.surface },
        { paddingTop: { desktop: '4.5rem', mobile: '3rem' }, paddingBottom: { desktop: '4.5rem', mobile: '3rem' } },
      ),
      [`${p}_process_wrap`]: block(
        `${p}_process_wrap`,
        'container',
        'Process wrapper',
        `${p}_process`,
        [`${p}_process_title`, `${p}_process_grid`],
        { maxWidth: { desktop: '1050px' } },
        { paddingLeft: { desktop: '1.5rem' }, paddingRight: { desktop: '1.5rem' } },
      ),
      [`${p}_process_title`]: block(
        `${p}_process_title`,
        'heading',
        'Process title',
        `${p}_process_wrap`,
        [],
        {},
        { marginBottom: { desktop: '2rem' } },
        { color: spec.text, textAlign: { desktop: 'center' }, fontSize: { desktop: '2.2rem' }, fontWeight: { desktop: '900' } },
        {},
        {},
        {},
        { text: 'Launch flow designed for speed', level: 2 },
      ),
      [`${p}_process_grid`]: block(
        `${p}_process_grid`,
        'grid',
        'Process grid',
        `${p}_process_wrap`,
        spec.process.map((_, index) => `${p}_step_${index + 1}`),
        { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: 'repeat(3, minmax(0, 1fr))' }, gap: { desktop: '1rem' } },
      ),
      ...Object.fromEntries(spec.process.map((step, index) => [
        `${p}_step_${index + 1}`,
        block(
          `${p}_step_${index + 1}`,
          'text',
          `Launch step ${index + 1}`,
          `${p}_process_grid`,
          [],
          { backgroundColor: spec.bg },
          { paddingTop: { desktop: '1.4rem' }, paddingBottom: { desktop: '1.4rem' }, paddingLeft: { desktop: '1.2rem' }, paddingRight: { desktop: '1.2rem' }, marginBottom: { desktop: '0', mobile: '1rem' } },
          { color: spec.muted, lineHeight: { desktop: '1.65' }, fontSize: { desktop: '0.95rem' } },
          { borderRadius: { desktop: '1.2rem' }, borderStyle: 'solid', borderWidth: { desktop: '1px' }, borderColor: `${spec.accent}22` },
          {},
          {},
          { htmlContent: richText(`<strong style="color:${spec.text}">0${index + 1}.</strong> ${step}`) },
        )
      ])),
      [`${p}_lead`]: block(
        `${p}_lead`,
        'section',
        'Final lead capture section',
        `${p}_root`,
        [`${p}_lead_wrap`],
        { backgroundColor: spec.bg },
        { paddingTop: { desktop: '5rem', mobile: '3rem' }, paddingBottom: { desktop: '5rem', mobile: '3rem' } },
      ),
      [`${p}_lead_wrap`]: block(
        `${p}_lead_wrap`,
        'container',
        'Lead capture card',
        `${p}_lead`,
        [`${p}_lead_title`, `${p}_lead_text`, `${p}_lead_form`],
        { maxWidth: { desktop: '820px' }, backgroundColor: spec.surface },
        { paddingTop: { desktop: '3rem' }, paddingBottom: { desktop: '3rem' }, paddingLeft: { desktop: '2rem', mobile: '1.25rem' }, paddingRight: { desktop: '2rem', mobile: '1.25rem' }, marginLeft: { desktop: 'auto' }, marginRight: { desktop: 'auto' } },
        { textAlign: { desktop: 'center' } },
        { borderRadius: { desktop: '2rem' }, borderStyle: 'solid', borderWidth: { desktop: '1px' }, borderColor: `${spec.accent}33` },
        { boxShadow: `0 28px 90px ${spec.accent}22` },
      ),
      [`${p}_lead_title`]: block(
        `${p}_lead_title`,
        'heading',
        'Lead title',
        `${p}_lead_wrap`,
        [],
        {},
        { marginBottom: { desktop: '0.75rem' } },
        { color: spec.text, fontSize: { desktop: '2.2rem', mobile: '1.7rem' }, fontWeight: { desktop: '900' } },
        {},
        {},
        {},
        { text: `Ready to upgrade your ${spec.audience.toLowerCase()} funnel?`, level: 2 },
      ),
      [`${p}_lead_text`]: block(
        `${p}_lead_text`,
        'text',
        'Lead supporting text',
        `${p}_lead_wrap`,
        [],
        {},
        { marginBottom: { desktop: '1.6rem' } },
        { color: spec.muted, lineHeight: { desktop: '1.7' } },
        {},
        {},
        {},
        { htmlContent: richText('Capture demand, qualify leads, and publish a polished page without waiting on a developer queue.') },
      ),
      [`${p}_lead_form`]: block(
        `${p}_lead_form`,
        'form',
        'Conversion form',
        `${p}_lead_wrap`,
        [`${p}_lead_input`, `${p}_lead_submit`],
        { maxWidth: { desktop: '520px' } },
        { marginLeft: { desktop: 'auto' }, marginRight: { desktop: 'auto' } },
        { textAlign: { desktop: 'left' } },
        {},
        {},
        {},
        { submitMethod: 'POST', successMessage: 'Thanks — your request has been captured.', errorMessage: 'Submission failed. Please try again.' },
      ),
      [`${p}_lead_input`]: block(
        `${p}_lead_input`,
        'input',
        'Email capture input',
        `${p}_lead_form`,
        [],
        {},
        { marginBottom: { desktop: '0.8rem' } },
        {},
        {},
        {},
        {},
        { name: 'email', label: 'Work email', placeholder: 'you@company.com', inputType: 'email', required: true },
      ),
      [`${p}_lead_submit`]: block(
        `${p}_lead_submit`,
        'submit-button',
        'Lead submit button',
        `${p}_lead_form`,
        [],
        {},
        {},
        {},
        {},
        {},
        {},
        { label: spec.cta },
      ),
    },
  };

  return {
    templateId: spec.id,
    name: spec.name,
    description: spec.description,
    category: spec.category,
    schema,
  };
}

const baseBenefits = (noun: string): Array<{ title: string; body: string }> => [
  { title: 'Premium first impression', body: `A sharp visual hierarchy designed to make ${noun} feel established, trustworthy, and ready to buy from.` },
  { title: 'Conversion-focused structure', body: 'Hero, proof, benefits, process, and lead capture are arranged to reduce friction and increase intent.' },
  { title: 'Mobile-ready polish', body: 'Responsive spacing, typography, and single-column fallbacks keep the experience elegant on every screen.' },
];

const specs: ProfessionalTemplateSpec[] = [
  { id: 'ai_startup_os', name: 'AI Startup OS', description: 'Dark, investor-grade AI SaaS landing page for waitlists and demos.', category: 'SAAS', audience: 'AI founders', headline: 'Turn your AI product into a category-defining launch', subheadline: 'A cinematic SaaS page for teams selling automation, copilots, agents, and workflow intelligence.', cta: 'Launch the AI demo', accent: '#8b5cf6', accent2: '#06b6d4', bg: '#070716', surface: '#111126', text: '#f8fafc', muted: '#a5b4fc', proof: ['Built for demo bookings', 'VC-grade launch narrative', 'Edge-fast page experience'], benefits: baseBenefits('AI buyers'), process: ['Position the product outcome clearly.', 'Show proof and workflow value.', 'Capture qualified demo requests.'] },
  { id: 'fintech_neobank', name: 'Fintech Neobank Pro', description: 'Secure, premium landing page for fintech apps and digital banking.', category: 'SAAS', audience: 'fintech teams', headline: 'A trust-first landing page for modern finance products', subheadline: 'Explain security, speed, and account value with a polished conversion flow made for regulated markets.', cta: 'Start secure onboarding', accent: '#22c55e', accent2: '#38bdf8', bg: '#03130d', surface: '#092018', text: '#ecfdf5', muted: '#a7f3d0', proof: ['Security-led messaging', 'Built for onboarding', 'Clear compliance cues'], benefits: baseBenefits('finance customers'), process: ['Lead with trust and clarity.', 'Explain the account advantage.', 'Route visitors into onboarding.'] },
  { id: 'cybersecurity_mssp', name: 'Cybersecurity MSSP Command', description: 'High-authority cybersecurity page for managed security providers.', category: 'AGENCY', audience: 'security buyers', headline: 'Make your cybersecurity offer impossible to ignore', subheadline: 'A bold, technical-but-clear landing page for MSSPs, SOC teams, audits, and incident response offers.', cta: 'Book a security assessment', accent: '#ef4444', accent2: '#f97316', bg: '#100607', surface: '#1f1012', text: '#fff7ed', muted: '#fecaca', proof: ['SOC-ready messaging', 'Risk reduction narrative', 'Enterprise consultation flow'], benefits: baseBenefits('security decision makers'), process: ['Surface urgent business risk.', 'Present your protection framework.', 'Convert interest into assessment calls.'] },
  { id: 'devtools_api', name: 'Developer API Launch', description: 'Technical SaaS template for APIs, SDKs, and developer platforms.', category: 'SAAS', audience: 'developer platforms', headline: 'Ship a developer landing page that explains your API fast', subheadline: 'Position docs, reliability, and integration wins in a page that speaks to engineering and product buyers.', cta: 'Open the API sandbox', accent: '#3b82f6', accent2: '#14b8a6', bg: '#050b16', surface: '#0d1728', text: '#eff6ff', muted: '#bfdbfe', proof: ['SDK-ready story', 'Docs-first conversion', 'Performance proof'], benefits: baseBenefits('technical users'), process: ['Clarify the integration promise.', 'Show speed and reliability.', 'Push developers into sandbox usage.'] },
  { id: 'hrtech_recruiting', name: 'HRTech Recruiting Suite', description: 'Modern recruiting platform template for HR SaaS and staffing tools.', category: 'SAAS', audience: 'HR leaders', headline: 'Hire faster with a recruiting page built for decisive teams', subheadline: 'Showcase pipeline clarity, automation, and candidate experience with enterprise-grade polish.', cta: 'Improve hiring workflow', accent: '#f59e0b', accent2: '#ec4899', bg: '#160f04', surface: '#241907', text: '#fffbeb', muted: '#fde68a', proof: ['Pipeline-first message', 'Built for demos', 'HR-friendly conversion'], benefits: baseBenefits('HR teams'), process: ['Identify hiring bottlenecks.', 'Show automation and visibility.', 'Capture demo-ready leads.'] },
  { id: 'martech_analytics', name: 'MarTech Analytics Board', description: 'Analytics SaaS template for dashboards, attribution, and growth teams.', category: 'SAAS', audience: 'growth marketers', headline: 'Make your analytics product feel instantly actionable', subheadline: 'A clean, metrics-led landing page for attribution, dashboards, campaign intelligence, and revenue teams.', cta: 'See the dashboard', accent: '#06b6d4', accent2: '#6366f1', bg: '#041016', surface: '#0b1f29', text: '#ecfeff', muted: '#a5f3fc', proof: ['Built around metrics', 'Attribution-ready layout', 'Growth-team messaging'], benefits: baseBenefits('marketing leaders'), process: ['State the measurement gap.', 'Show insight-to-action flow.', 'Invite a dashboard walkthrough.'] },
  { id: 'ecommerce_brand', name: 'Ecommerce Brand Launch', description: 'Premium ecommerce template for direct-to-consumer brands.', category: 'DROPSHIPPING', audience: 'DTC brands', headline: 'Launch a product page that makes your brand feel premium', subheadline: 'Create a fast, persuasive storefront narrative for hero products, bundles, and paid traffic campaigns.', cta: 'Build the product funnel', accent: '#fb7185', accent2: '#f97316', bg: '#17080b', surface: '#251014', text: '#fff1f2', muted: '#fecdd3', proof: ['Paid traffic ready', 'Product-first structure', 'Trust-building sections'], benefits: baseBenefits('online shoppers'), process: ['Lead with product transformation.', 'Layer proof and benefits.', 'Capture clicks and purchases.'] },
  { id: 'beauty_skincare', name: 'Beauty Skincare Glow', description: 'Elegant skincare and beauty product landing page.', category: 'DROPSHIPPING', audience: 'beauty shoppers', headline: 'Give your skincare offer a luxury editorial presence', subheadline: 'A soft, premium template for serums, routines, beauty kits, and creator-led product drops.', cta: 'Reveal the routine', accent: '#f9a8d4', accent2: '#c084fc', bg: '#170b12', surface: '#26131f', text: '#fff7fb', muted: '#fbcfe8', proof: ['Beauty-native visuals', 'Routine-led persuasion', 'Trust and ingredient flow'], benefits: baseBenefits('beauty buyers'), process: ['Frame the skin outcome.', 'Explain routine and ingredients.', 'Convert into purchase intent.'] },
  { id: 'jewelry_luxury', name: 'Luxury Jewelry Atelier', description: 'High-end landing page for jewelry collections and premium accessories.', category: 'DROPSHIPPING', audience: 'luxury shoppers', headline: 'Present your jewelry collection like a private atelier', subheadline: 'A refined template for limited drops, engagement collections, custom pieces, and boutique brands.', cta: 'Explore the collection', accent: '#eab308', accent2: '#f97316', bg: '#12100a', surface: '#211c10', text: '#fefce8', muted: '#fde68a', proof: ['Luxury editorial feel', 'Collection-first layout', 'Boutique conversion path'], benefits: baseBenefits('luxury customers'), process: ['Create desire through positioning.', 'Show quality and scarcity.', 'Guide visitors into collection viewing.'] },
  { id: 'pet_store', name: 'Pet Store Happy Paws', description: 'Warm ecommerce template for pet products and subscription boxes.', category: 'DROPSHIPPING', audience: 'pet owners', headline: 'A playful page that helps pet products sell with trust', subheadline: 'Perfect for food, toys, grooming, pet wellness, subscription boxes, and local pet brands.', cta: 'Build the pet funnel', accent: '#84cc16', accent2: '#f59e0b', bg: '#0d1305', surface: '#172109', text: '#f7fee7', muted: '#d9f99d', proof: ['Friendly brand tone', 'Subscription ready', 'Benefit-led product story'], benefits: baseBenefits('pet parents'), process: ['Lead with pet happiness.', 'Explain safety and value.', 'Capture orders or subscriptions.'] },
  { id: 'realestate_luxury_condo', name: 'Luxury Condo Showcase', description: 'Premium real estate landing page for condos and new developments.', category: 'REAL_ESTATE', audience: 'property buyers', headline: 'Showcase a property development with cinematic confidence', subheadline: 'A luxury sales page for condos, villas, towers, and premium real estate inventory.', cta: 'Schedule a private tour', accent: '#c084fc', accent2: '#38bdf8', bg: '#0b0a14', surface: '#17152a', text: '#faf5ff', muted: '#ddd6fe', proof: ['Private tour CTA', 'Amenity-led storytelling', 'Investor-friendly sections'], benefits: baseBenefits('property buyers'), process: ['Position the location and lifestyle.', 'Highlight amenities and scarcity.', 'Convert visitors into tour bookings.'] },
  { id: 'realestate_agent', name: 'Elite Agent Personal Brand', description: 'Personal brand page for realtors and property consultants.', category: 'REAL_ESTATE', audience: 'real estate agents', headline: 'Turn your realtor profile into a lead-generating brand', subheadline: 'A polished page for agents who need listings, testimonials, local authority, and consultation requests.', cta: 'Book a valuation call', accent: '#0ea5e9', accent2: '#14b8a6', bg: '#06121b', surface: '#0c2230', text: '#f0f9ff', muted: '#bae6fd', proof: ['Personal authority layout', 'Listing-ready sections', 'Valuation CTA flow'], benefits: baseBenefits('home sellers'), process: ['Build local trust.', 'Show market expertise.', 'Capture valuation and buyer leads.'] },
  { id: 'architecture_studio', name: 'Architecture Studio Minimal', description: 'Portfolio-led template for architects and design studios.', category: 'AGENCY', audience: 'architecture studios', headline: 'A minimal studio page that makes projects feel iconic', subheadline: 'Present interiors, architecture, planning, and design services with gallery-like restraint and conversion clarity.', cta: 'Start a design consultation', accent: '#94a3b8', accent2: '#f8fafc', bg: '#0b0f14', surface: '#151b23', text: '#f8fafc', muted: '#cbd5e1', proof: ['Portfolio-first rhythm', 'Premium service positioning', 'Consultation lead flow'], benefits: baseBenefits('design clients'), process: ['Lead with aesthetic authority.', 'Clarify service scope.', 'Invite the right project inquiries.'] },
  { id: 'dental_clinic', name: 'Dental Clinic Smile Pro', description: 'Conversion-ready dental clinic booking page.', category: 'MEDICAL', audience: 'dental clinics', headline: 'Make dental bookings feel simple, safe, and premium', subheadline: 'A trustworthy page for cosmetic dentistry, implants, checkups, and family dental care.', cta: 'Book a dental visit', accent: '#38bdf8', accent2: '#22c55e', bg: '#06151a', surface: '#0d2630', text: '#ecfeff', muted: '#a5f3fc', proof: ['Booking-first design', 'Trust and care messaging', 'Treatment benefits layout'], benefits: baseBenefits('patients'), process: ['Reduce appointment anxiety.', 'Explain treatment benefits.', 'Route patients into booking.'] },
  { id: 'therapy_practice', name: 'Therapy Practice Calm', description: 'Warm mental health and therapy landing page.', category: 'MEDICAL', audience: 'therapy practices', headline: 'A calm digital front door for therapy and care', subheadline: 'Built for therapists, counselors, clinics, and wellness practices that need compassionate conversion.', cta: 'Request a confidential call', accent: '#2dd4bf', accent2: '#a78bfa', bg: '#051311', surface: '#0d2420', text: '#f0fdfa', muted: '#99f6e4', proof: ['Compassionate tone', 'Privacy-first CTA', 'Care journey sections'], benefits: baseBenefits('clients seeking support'), process: ['Create emotional safety.', 'Explain care options.', 'Invite a confidential consultation.'] },
  { id: 'medspa_aesthetic', name: 'Medspa Aesthetic Luxe', description: 'Luxury medspa template for injectables, laser, and aesthetic treatments.', category: 'MEDICAL', audience: 'aesthetic clinics', headline: 'Give your medspa treatments a luxury conversion experience', subheadline: 'A premium page for injectables, skincare, laser, body contouring, and consultations.', cta: 'Book a treatment consult', accent: '#f0abfc', accent2: '#fb7185', bg: '#160b16', surface: '#271427', text: '#fdf4ff', muted: '#f5d0fe', proof: ['Treatment-ready sections', 'Luxury clinic tone', 'Consult-first conversion'], benefits: baseBenefits('aesthetic clients'), process: ['Show the transformation.', 'Build clinical trust.', 'Capture consult requests.'] },
  { id: 'online_bootcamp', name: 'Online Bootcamp Authority', description: 'High-converting cohort and bootcamp landing page.', category: 'ONLINE_COURSE', audience: 'course creators', headline: 'Launch your next cohort with authority and urgency', subheadline: 'Built for bootcamps, masterminds, cohort courses, certifications, and professional training offers.', cta: 'Open cohort enrollment', accent: '#6366f1', accent2: '#f59e0b', bg: '#090b18', surface: '#15172b', text: '#eef2ff', muted: '#c7d2fe', proof: ['Cohort-ready flow', 'Outcome-led curriculum', 'Enrollment CTA'], benefits: baseBenefits('students'), process: ['Lead with the promised skill.', 'Break down curriculum and proof.', 'Push visitors into enrollment.'] },
  { id: 'language_school', name: 'Language School Global', description: 'Friendly education template for language schools and tutors.', category: 'ONLINE_COURSE', audience: 'language schools', headline: 'A language learning page that feels global and achievable', subheadline: 'Promote online classes, tutors, placement tests, and learning paths with polished clarity.', cta: 'Take the placement test', accent: '#22c55e', accent2: '#3b82f6', bg: '#06130a', surface: '#0f2414', text: '#f0fdf4', muted: '#bbf7d0', proof: ['Class-ready messaging', 'Placement test CTA', 'Progress-focused layout'], benefits: baseBenefits('learners'), process: ['Clarify the learning outcome.', 'Show levels and support.', 'Convert into placement or trial.'] },
  { id: 'coaching_high_ticket', name: 'High-Ticket Coaching Funnel', description: 'Premium coaching and consulting landing page.', category: 'ONLINE_COURSE', audience: 'coaches', headline: 'Position your coaching offer like a premium transformation', subheadline: 'A high-ticket funnel for business coaching, life coaching, executive advisory, and premium programs.', cta: 'Apply for coaching', accent: '#f97316', accent2: '#eab308', bg: '#160d05', surface: '#261709', text: '#fff7ed', muted: '#fed7aa', proof: ['Application-led CTA', 'Transformation narrative', 'Premium authority sections'], benefits: baseBenefits('premium clients'), process: ['Name the costly problem.', 'Show your unique mechanism.', 'Invite qualified applications.'] },
  { id: 'plumber_emergency', name: 'Emergency Plumber Local', description: 'Local service landing page for plumbers and emergency repairs.', category: 'LOCAL_SERVICES', audience: 'local service teams', headline: 'Book more emergency plumbing jobs from local search', subheadline: 'A direct-response service page for urgent repairs, quotes, phone calls, and neighborhood trust.', cta: 'Request emergency help', accent: '#0ea5e9', accent2: '#f97316', bg: '#06111a', surface: '#0d2233', text: '#eff6ff', muted: '#bae6fd', proof: ['Local call-ready CTA', 'Trust-first service flow', 'Emergency intent messaging'], benefits: baseBenefits('homeowners'), process: ['Highlight urgent availability.', 'Explain service coverage.', 'Convert visitors into calls.'] },
  { id: 'law_firm', name: 'Law Firm Authority', description: 'Professional legal landing page for consultations.', category: 'LOCAL_SERVICES', audience: 'law firms', headline: 'A legal landing page built for trust and consultations', subheadline: 'Present practice areas, credibility, and intake flow without looking generic or dated.', cta: 'Request a case review', accent: '#f59e0b', accent2: '#64748b', bg: '#11100b', surface: '#211e14', text: '#fffbeb', muted: '#fde68a', proof: ['Authority-first design', 'Case review CTA', 'Practice-area clarity'], benefits: baseBenefits('legal clients'), process: ['Lead with the legal outcome.', 'Clarify practice fit.', 'Route visitors into intake.'] },
  { id: 'cleaning_service', name: 'Cleaning Service Spark', description: 'Booking page for home and office cleaning companies.', category: 'LOCAL_SERVICES', audience: 'cleaning companies', headline: 'Turn cleaning searches into booked appointments', subheadline: 'A crisp page for recurring cleaning, deep cleans, move-outs, and office cleaning contracts.', cta: 'Get a cleaning quote', accent: '#22d3ee', accent2: '#22c55e', bg: '#051317', surface: '#0b242a', text: '#ecfeff', muted: '#a5f3fc', proof: ['Quote-led funnel', 'Before/after friendly', 'Recurring service ready'], benefits: baseBenefits('busy customers'), process: ['Show the clean-life benefit.', 'Explain packages and quality.', 'Capture quote requests.'] },
  { id: 'roofing_contractor', name: 'Roofing Contractor Pro', description: 'Lead-generation template for roofing and exterior contractors.', category: 'LOCAL_SERVICES', audience: 'roofing contractors', headline: 'Win more roofing estimates with a stronger local page', subheadline: 'A rugged, trustworthy template for roof repair, replacement, inspections, and storm restoration.', cta: 'Schedule a roof inspection', accent: '#f97316', accent2: '#0ea5e9', bg: '#150d07', surface: '#24170d', text: '#fff7ed', muted: '#fed7aa', proof: ['Inspection CTA flow', 'Storm-response messaging', 'Trust and warranty sections'], benefits: baseBenefits('homeowners'), process: ['Explain the roof risk.', 'Show inspection and warranty value.', 'Capture estimate-ready leads.'] },
  { id: 'gym_membership', name: 'Gym Membership Drive', description: 'Fitness template for gyms and studios.', category: 'FITNESS', audience: 'gym owners', headline: 'Fill your gym with a membership page that motivates action', subheadline: 'Promote classes, transformations, memberships, and trials with bold, energetic conversion design.', cta: 'Claim a free trial', accent: '#ef4444', accent2: '#facc15', bg: '#160707', surface: '#271010', text: '#fef2f2', muted: '#fecaca', proof: ['Trial-ready CTA', 'Transformation story', 'Membership conversion flow'], benefits: baseBenefits('fitness members'), process: ['Lead with the fitness identity.', 'Show community and programming.', 'Convert into trial bookings.'] },
  { id: 'yoga_studio', name: 'Yoga Studio Serenity', description: 'Calm wellness template for yoga and pilates studios.', category: 'FITNESS', audience: 'wellness studios', headline: 'Create a serene studio page that turns interest into class bookings', subheadline: 'A graceful template for yoga, pilates, breathwork, retreats, and mindful movement offers.', cta: 'Book a first class', accent: '#2dd4bf', accent2: '#f9a8d4', bg: '#071310', surface: '#10231e', text: '#f0fdfa', muted: '#99f6e4', proof: ['Class-booking flow', 'Calm premium visuals', 'Teacher trust sections'], benefits: baseBenefits('wellness clients'), process: ['Communicate the feeling.', 'Show class options and guides.', 'Route visitors to booking.'] },
  { id: 'nutritionist', name: 'Nutritionist Transformation', description: 'Personal nutrition coaching landing page.', category: 'FITNESS', audience: 'nutrition coaches', headline: 'Make your nutrition plan feel personalized and achievable', subheadline: 'A conversion page for dietitians, nutritionists, meal plans, habit coaching, and body transformation programs.', cta: 'Start a nutrition consult', accent: '#84cc16', accent2: '#22c55e', bg: '#0b1305', surface: '#17220b', text: '#f7fee7', muted: '#d9f99d', proof: ['Consult-first CTA', 'Habit-focused story', 'Coach authority layout'], benefits: baseBenefits('health clients'), process: ['Meet visitors where they are.', 'Explain your plan and support.', 'Capture consultation requests.'] },
  { id: 'coffee_shop', name: 'Coffee Shop Artisan', description: 'Restaurant template for cafes, roasters, and specialty shops.', category: 'RESTAURANT', audience: 'coffee shops', headline: 'Make your cafe feel like the neighborhood’s favorite ritual', subheadline: 'A warm page for cafes, roasters, coffee subscriptions, seasonal menus, and local pickup.', cta: 'View today’s menu', accent: '#a16207', accent2: '#f97316', bg: '#120d08', surface: '#21170f', text: '#fff7ed', muted: '#fed7aa', proof: ['Menu-first flow', 'Local warmth', 'Pickup and subscription ready'], benefits: baseBenefits('coffee lovers'), process: ['Create aroma and atmosphere.', 'Show menu and signature items.', 'Drive visits, orders, or subscriptions.'] },
  { id: 'catering_company', name: 'Catering Event Pro', description: 'Lead-gen template for catering and events.', category: 'RESTAURANT', audience: 'catering teams', headline: 'Win more event inquiries with a polished catering page', subheadline: 'Built for weddings, corporate events, private dinners, menus, and tasting bookings.', cta: 'Request event catering', accent: '#eab308', accent2: '#ef4444', bg: '#141006', surface: '#251d0a', text: '#fefce8', muted: '#fde68a', proof: ['Event inquiry CTA', 'Menu and service clarity', 'Premium hospitality feel'], benefits: baseBenefits('event planners'), process: ['Position your event experience.', 'Show menu and service options.', 'Capture detailed catering inquiries.'] },
  { id: 'food_truck', name: 'Food Truck Launch', description: 'Energetic restaurant template for food trucks and popups.', category: 'RESTAURANT', audience: 'food truck brands', headline: 'Turn your food truck into a destination people chase', subheadline: 'A bold page for schedules, menus, popups, catering, and social-first food brands.', cta: 'Find the truck', accent: '#f97316', accent2: '#22c55e', bg: '#160b04', surface: '#271408', text: '#fff7ed', muted: '#fdba74', proof: ['Location-ready layout', 'Menu and catering CTA', 'Social-friendly energy'], benefits: baseBenefits('hungry customers'), process: ['Lead with craveable identity.', 'Show menu and weekly locations.', 'Convert into visits or catering.'] },
  { id: 'creative_agency', name: 'Creative Agency Pitch', description: 'Bold agency template for creative studios.', category: 'AGENCY', audience: 'creative agencies', headline: 'Pitch your agency like a brand people want to hire', subheadline: 'A stylish landing page for strategy, branding, creative direction, campaigns, and studio portfolios.', cta: 'Start a creative brief', accent: '#ec4899', accent2: '#8b5cf6', bg: '#150716', surface: '#251026', text: '#fdf4ff', muted: '#f5d0fe', proof: ['Portfolio-ready sections', 'Brief-first CTA', 'Bold studio positioning'], benefits: baseBenefits('brand teams'), process: ['Show creative point of view.', 'Explain capabilities and outcomes.', 'Capture project briefs.'] },
  { id: 'b2b_consulting', name: 'B2B Consulting Authority', description: 'Consulting firm landing page for enterprise services.', category: 'AGENCY', audience: 'consulting firms', headline: 'Package your consulting expertise into a premium growth page', subheadline: 'A serious, boardroom-ready template for strategy, operations, finance, transformation, and B2B advisory.', cta: 'Book an advisory call', accent: '#64748b', accent2: '#3b82f6', bg: '#0b0f14', surface: '#151b23', text: '#f8fafc', muted: '#cbd5e1', proof: ['Executive-ready tone', 'Advisory CTA flow', 'Outcome-led sections'], benefits: baseBenefits('executive buyers'), process: ['Define the strategic problem.', 'Show your operating model.', 'Invite advisory conversations.'] },
  { id: 'pr_agency', name: 'PR Agency Momentum', description: 'Public relations and communications landing page.', category: 'AGENCY', audience: 'PR agencies', headline: 'Make your PR offer feel urgent, credible, and newsworthy', subheadline: 'Promote launches, media relations, crisis comms, founder visibility, and reputation programs.', cta: 'Plan a media push', accent: '#06b6d4', accent2: '#f59e0b', bg: '#061216', surface: '#0d242b', text: '#ecfeff', muted: '#a5f3fc', proof: ['Media-ready narrative', 'Campaign CTA flow', 'Reputation-led proof'], benefits: baseBenefits('founders and brands'), process: ['Define the visibility gap.', 'Show campaign mechanics.', 'Capture strategy calls.'] },
  { id: 'photographer_portfolio', name: 'Photographer Portfolio Luxe', description: 'Portfolio and booking template for photographers.', category: 'CREATOR_BIO', audience: 'photographers', headline: 'Turn your photography portfolio into a premium booking page', subheadline: 'A refined template for weddings, portraits, commercial shoots, studios, and creative bookings.', cta: 'Book a shoot', accent: '#f8fafc', accent2: '#94a3b8', bg: '#09090b', surface: '#18181b', text: '#fafafa', muted: '#d4d4d8', proof: ['Portfolio-led flow', 'Booking-first CTA', 'Premium visual pacing'], benefits: baseBenefits('photo clients'), process: ['Set the visual mood.', 'Clarify packages and availability.', 'Capture booking inquiries.'] },
  { id: 'podcaster_media', name: 'Podcaster Media Kit', description: 'Creator landing page for podcasts and media brands.', category: 'CREATOR_BIO', audience: 'podcasters', headline: 'Package your podcast into a sponsor-ready media kit', subheadline: 'A sharp page for episodes, audience stats, sponsors, bookings, and newsletter growth.', cta: 'View the media kit', accent: '#a78bfa', accent2: '#f472b6', bg: '#0f0b18', surface: '#1d1530', text: '#faf5ff', muted: '#ddd6fe', proof: ['Sponsor-ready structure', 'Audience proof sections', 'Newsletter and booking CTA'], benefits: baseBenefits('listeners and sponsors'), process: ['Lead with the show promise.', 'Show audience and credibility.', 'Convert into sponsors or subscribers.'] },
  { id: 'author_book_launch', name: 'Author Book Launch', description: 'Book launch template for authors and publishers.', category: 'CREATOR_BIO', audience: 'authors', headline: 'Launch your book with a page that sells the promise', subheadline: 'A polished template for preorders, reviews, author bios, speaking, and launch campaigns.', cta: 'Preorder the book', accent: '#f59e0b', accent2: '#8b5cf6', bg: '#120e07', surface: '#221a0e', text: '#fffbeb', muted: '#fde68a', proof: ['Preorder CTA flow', 'Review-ready sections', 'Author authority layout'], benefits: baseBenefits('readers'), process: ['Hook readers with the premise.', 'Show credibility and praise.', 'Drive preorders and speaking inquiries.'] },
  { id: 'newsletter_creator', name: 'Newsletter Growth Hub', description: 'Newsletter landing page for creators and media operators.', category: 'CREATOR_BIO', audience: 'newsletter creators', headline: 'Grow your newsletter with a page that explains the value instantly', subheadline: 'A conversion page for paid newsletters, free lists, communities, sponsorships, and creator funnels.', cta: 'Join the newsletter', accent: '#22c55e', accent2: '#06b6d4', bg: '#06120a', surface: '#102318', text: '#f0fdf4', muted: '#bbf7d0', proof: ['Subscriber-first flow', 'Sponsor-friendly proof', 'Creator monetization ready'], benefits: baseBenefits('subscribers'), process: ['State the weekly value.', 'Show proof and topics.', 'Capture high-intent subscribers.'] },
  { id: 'event_conference', name: 'Event Conference Pro', description: 'Conference landing page for tickets, agenda, and sponsors.', category: 'AGENCY', audience: 'event teams', headline: 'Launch an event page that sells the room before doors open', subheadline: 'Built for conferences, summits, workshops, festivals, agendas, speakers, and sponsor packages.', cta: 'Reserve a ticket', accent: '#6366f1', accent2: '#f97316', bg: '#090b18', surface: '#15172b', text: '#eef2ff', muted: '#c7d2fe', proof: ['Ticket CTA flow', 'Speaker-ready sections', 'Sponsor proof layout'], benefits: baseBenefits('attendees'), process: ['Frame the event outcome.', 'Show agenda and speakers.', 'Convert visitors into ticket buyers.'] },
  { id: 'nonprofit_campaign', name: 'Nonprofit Campaign Impact', description: 'Donation and campaign page for nonprofits.', category: 'LOCAL_SERVICES', audience: 'nonprofit teams', headline: 'Turn your cause into an impact page people act on', subheadline: 'A heartfelt, clear page for donations, volunteers, campaigns, community programs, and awareness drives.', cta: 'Support the campaign', accent: '#22c55e', accent2: '#f59e0b', bg: '#06130a', surface: '#102416', text: '#f0fdf4', muted: '#bbf7d0', proof: ['Donation-ready flow', 'Impact-first storytelling', 'Volunteer CTA support'], benefits: baseBenefits('supporters'), process: ['Make the cause tangible.', 'Show impact and accountability.', 'Invite donations or volunteers.'] },
  { id: 'saas_mobile_app', name: 'Mobile App SaaS', description: 'App launch page for mobile SaaS and consumer apps.', category: 'SAAS', audience: 'app startups', headline: 'Launch your mobile app with a page that feels App Store ready', subheadline: 'A sleek template for productivity apps, social apps, fintech apps, consumer tools, and waitlists.', cta: 'Join the app waitlist', accent: '#38bdf8', accent2: '#a78bfa', bg: '#06111a', surface: '#0d2230', text: '#f0f9ff', muted: '#bae6fd', proof: ['Waitlist-ready flow', 'Feature-led app story', 'Mobile-first polish'], benefits: baseBenefits('app users'), process: ['Explain the everyday problem.', 'Show the app workflow.', 'Capture waitlist demand.'] },
  { id: 'insurance_broker', name: 'Insurance Broker Trust', description: 'Lead generation page for insurance brokers and agencies.', category: 'LOCAL_SERVICES', audience: 'insurance brokers', headline: 'A trust-first page for insurance quotes and consultations', subheadline: 'Explain coverage options, reduce confusion, and capture quote requests for home, auto, life, and business insurance.', cta: 'Compare coverage options', accent: '#2563eb', accent2: '#22c55e', bg: '#06101e', surface: '#0d1f35', text: '#eff6ff', muted: '#bfdbfe', proof: ['Quote-ready CTA', 'Coverage clarity sections', 'Trust and advisory tone'], benefits: baseBenefits('policy shoppers'), process: ['Simplify the coverage decision.', 'Show advisory value.', 'Capture quote-ready leads.'] },
  { id: 'accounting_firm', name: 'Accounting Firm Clarity', description: 'Professional template for accountants and tax advisors.', category: 'LOCAL_SERVICES', audience: 'accounting firms', headline: 'Make accounting services feel clear, premium, and proactive', subheadline: 'A polished page for tax planning, bookkeeping, CFO services, and business advisory.', cta: 'Book a finance review', accent: '#22c55e', accent2: '#64748b', bg: '#06130a', surface: '#102318', text: '#f0fdf4', muted: '#bbf7d0', proof: ['Advisory CTA flow', 'Service clarity blocks', 'Trust-first finance tone'], benefits: baseBenefits('business owners'), process: ['Name the financial friction.', 'Show systems and advisory value.', 'Capture review calls.'] },
  { id: 'car_detailing', name: 'Car Detailing Studio', description: 'Local service page for auto detailing and ceramic coating.', category: 'LOCAL_SERVICES', audience: 'auto detailers', headline: 'Make your detailing service look as premium as the finish', subheadline: 'A sharp page for ceramic coating, paint correction, detailing packages, and booking requests.', cta: 'Book a detail package', accent: '#38bdf8', accent2: '#f8fafc', bg: '#050b10', surface: '#0d1821', text: '#f0f9ff', muted: '#bae6fd', proof: ['Package-ready layout', 'Premium auto feel', 'Booking CTA flow'], benefits: baseBenefits('car owners'), process: ['Show the visual transformation.', 'Explain packages and protection.', 'Convert into bookings.'] },
  { id: 'travel_agency', name: 'Travel Agency Escape', description: 'Luxury travel and itinerary planning landing page.', category: 'AGENCY', audience: 'travel planners', headline: 'Sell curated travel experiences with cinematic clarity', subheadline: 'A premium page for travel agencies, retreats, destination planners, and luxury itinerary services.', cta: 'Plan my escape', accent: '#06b6d4', accent2: '#f59e0b', bg: '#061216', surface: '#0e252b', text: '#ecfeff', muted: '#a5f3fc', proof: ['Itinerary CTA flow', 'Luxury experience tone', 'Destination-led sections'], benefits: baseBenefits('travel clients'), process: ['Paint the destination feeling.', 'Explain curated planning value.', 'Capture trip inquiries.'] },
  { id: 'hotel_boutique', name: 'Boutique Hotel Stay', description: 'Hospitality template for boutique hotels and resorts.', category: 'RESTAURANT', audience: 'boutique hotels', headline: 'Make your boutique stay feel irresistible before booking', subheadline: 'A hospitality page for rooms, amenities, local experiences, offers, and direct booking campaigns.', cta: 'Check availability', accent: '#c084fc', accent2: '#f59e0b', bg: '#100b16', surface: '#1d1428', text: '#faf5ff', muted: '#ddd6fe', proof: ['Direct-booking CTA', 'Amenity story flow', 'Luxury hospitality feel'], benefits: baseBenefits('travel guests'), process: ['Show the stay experience.', 'Highlight amenities and location.', 'Drive direct availability checks.'] },
  { id: 'wedding_planner', name: 'Wedding Planner Romance', description: 'Elegant landing page for wedding planners and venues.', category: 'AGENCY', audience: 'wedding planners', headline: 'Present your wedding planning service with unforgettable elegance', subheadline: 'A romantic, premium template for planners, venues, florists, and high-touch event services.', cta: 'Plan our wedding', accent: '#f9a8d4', accent2: '#eab308', bg: '#160b12', surface: '#26131d', text: '#fff7fb', muted: '#fbcfe8', proof: ['Inquiry-ready flow', 'Luxury event tone', 'Portfolio and service clarity'], benefits: baseBenefits('engaged couples'), process: ['Create emotional resonance.', 'Explain planning experience.', 'Capture wedding inquiries.'] },
  { id: 'interior_design', name: 'Interior Design Studio', description: 'Premium interior design and renovation landing page.', category: 'AGENCY', audience: 'interior designers', headline: 'Turn your interior design portfolio into premium project leads', subheadline: 'A refined template for interiors, renovations, styling, consultations, and studio portfolios.', cta: 'Start a room consult', accent: '#d6d3d1', accent2: '#a16207', bg: '#100d0b', surface: '#1f1a16', text: '#fafaf9', muted: '#d6d3d1', proof: ['Portfolio-led structure', 'Consultation CTA', 'Premium design pacing'], benefits: baseBenefits('home design clients'), process: ['Set the aesthetic standard.', 'Show process and project types.', 'Capture qualified design leads.'] },
  { id: 'manufacturing_b2b', name: 'Manufacturing B2B Precision', description: 'Industrial B2B template for manufacturers and suppliers.', category: 'AGENCY', audience: 'manufacturing firms', headline: 'Make complex manufacturing capabilities easy to trust', subheadline: 'A serious B2B landing page for suppliers, industrial services, machining, logistics, and enterprise buyers.', cta: 'Request a capability review', accent: '#f97316', accent2: '#64748b', bg: '#11100f', surface: '#211d19', text: '#fff7ed', muted: '#fed7aa', proof: ['Capability-first layout', 'Enterprise inquiry CTA', 'Procurement-friendly messaging'], benefits: baseBenefits('B2B buyers'), process: ['Clarify capabilities and standards.', 'Show reliability and process.', 'Capture RFQ-ready inquiries.'] },
  { id: 'logistics_freight', name: 'Logistics Freight Flow', description: 'B2B logistics and freight landing page.', category: 'AGENCY', audience: 'logistics companies', headline: 'Position your logistics service as the reliable route forward', subheadline: 'A conversion page for freight, warehousing, fulfillment, courier networks, and supply chain providers.', cta: 'Request a freight quote', accent: '#0ea5e9', accent2: '#22c55e', bg: '#06121b', surface: '#0d2230', text: '#f0f9ff', muted: '#bae6fd', proof: ['Quote-ready flow', 'Reliability-led sections', 'B2B procurement clarity'], benefits: baseBenefits('operations teams'), process: ['Name delivery and cost risk.', 'Explain network capability.', 'Capture quote requests.'] },
  { id: 'solar_energy', name: 'Solar Energy Savings', description: 'Clean energy landing page for solar installers.', category: 'LOCAL_SERVICES', audience: 'solar installers', headline: 'Convert solar interest into qualified savings consultations', subheadline: 'A clean, optimistic page for residential solar, batteries, energy audits, and installation quotes.', cta: 'Calculate solar savings', accent: '#facc15', accent2: '#22c55e', bg: '#141204', surface: '#25210a', text: '#fefce8', muted: '#fde68a', proof: ['Savings CTA flow', 'Clean energy trust', 'Consultation-ready sections'], benefits: baseBenefits('homeowners'), process: ['Lead with savings and control.', 'Explain installation and incentives.', 'Capture consultation requests.'] },
  { id: 'crypto_web3', name: 'Web3 Protocol Launch', description: 'Premium Web3 protocol and community landing page.', category: 'SAAS', audience: 'Web3 teams', headline: 'Launch your protocol with a page that feels credible beyond hype', subheadline: 'A polished template for wallets, protocols, communities, infrastructure, and token-gated products.', cta: 'Explore the protocol', accent: '#8b5cf6', accent2: '#22d3ee', bg: '#080716', surface: '#141225', text: '#f5f3ff', muted: '#ddd6fe', proof: ['Community-ready layout', 'Protocol clarity sections', 'Trust and utility narrative'], benefits: baseBenefits('Web3 users'), process: ['Explain utility in plain terms.', 'Show ecosystem and security.', 'Convert into community or product action.'] },

];

export const professionalTemplatePack: Record<string, LandingPageTemplate> = Object.fromEntries(
  specs.map((spec) => [spec.id, createProfessionalTemplate(spec)])
);

export const professionalTemplatePackCount = specs.length;
