import { LandingPageTemplate } from '../templates';

export const realEstateTemplate: LandingPageTemplate = {
  templateId: 'real_estate',
  name: 'Luxury Real Estate Property Page',
  description: 'High-end property lead generation page with image galleries, neighborhood detail grids, and agent contact form.',
  category: 'REAL_ESTATE',
  schema: {
    version: '1.0.0',
    pageId: 'landing_page_demo_1',
    title: 'Premium Property Funnel',
    slug: 'property',
    seo: {
      title: 'Modern Villas at Azure Coast | Elite Estates',
      description: 'Schedule a private, exclusive walkthrough of the spectacular Azure Coast villas. Panoramic ocean views, custom designs.',
      keywords: 'villa, luxury, real estate, beach',
    },
    theme: {
      primaryColor: '#0f172a', // Luxury slate dark
      secondaryColor: '#b45309', // Warm amber gold
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      fontHeading: 'Playfair Display',
      fontBody: 'Inter',
    },
    rootBlockId: 'root_block',
    blocks: {
      root_block: {
        id: 'root_block',
        type: 'container',
        name: 'Property Page Root',
        parentId: null,
        children: ['estate_hero_section', 'estate_grid_section'],
        layout: { display: { desktop: 'block' }, width: { desktop: '100%' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      estate_hero_section: {
        id: 'estate_hero_section',
        type: 'section',
        name: 'Estate Main Hero',
        parentId: 'root_block',
        children: ['estate_container'],
        layout: { backgroundColor: '#f8fafc' },
        spacing: { paddingTop: { desktop: '5rem' }, paddingBottom: { desktop: '5rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      estate_container: {
        id: 'estate_container',
        type: 'container',
        name: 'Estate Container',
        parentId: 'estate_hero_section',
        children: ['estate_title', 'estate_lead_form'],
        layout: {},
        spacing: { paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: { textAlign: { desktop: 'center' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      estate_title: {
        id: 'estate_title',
        type: 'heading',
        name: 'Estate Title',
        parentId: 'estate_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '1.5rem' } },
        typography: { fontSize: { desktop: '3rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: 'Azure Coast Luxury Villas', level: 1 },
      },
      estate_lead_form: {
        id: 'estate_lead_form',
        type: 'form',
        name: 'Private Walkthrough Form',
        parentId: 'estate_container',
        children: ['estate_submit_btn'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { submitMethod: 'SUPABASE', successMessage: 'Thank you. An Elite Estates representative will contact you to confirm.' },
      },
      estate_submit_btn: {
        id: 'estate_submit_btn',
        type: 'button',
        name: 'Estate Submit Button',
        parentId: 'estate_lead_form',
        children: [],
        layout: {},
        spacing: {},
        typography: {},
        border: { borderRadius: { desktop: '0.25rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: 'Schedule Private Walkthrough', variant: 'primary', action: { type: 'url', url: 'https://arena.ai' } },
      },
      estate_grid_section: {
        id: 'estate_grid_section',
        type: 'section',
        name: 'Properties Specs Grid Section',
        parentId: 'root_block',
        children: ['estate_grid_container'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '4rem' }, paddingBottom: { desktop: '4rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      estate_grid_container: {
        id: 'estate_grid_container',
        type: 'container',
        name: 'Grid Box',
        parentId: 'estate_grid_section',
        children: ['estate_grid_layout'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      estate_grid_layout: {
        id: 'estate_grid_layout',
        type: 'grid',
        name: 'Specs Columns Grid',
        parentId: 'estate_grid_container',
        children: ['estate_spec_1', 'estate_spec_2'],
        layout: { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: '1fr 1fr' }, gap: { desktop: '2rem' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      estate_spec_1: {
        id: 'estate_spec_1',
        type: 'container',
        name: 'Spec Card 1',
        parentId: 'estate_grid_layout',
        children: ['estate_spec_1_title', 'estate_spec_1_desc'],
        layout: { backgroundColor: '#f1f5f9' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      estate_spec_1_title: {
        id: 'estate_spec_1_title',
        type: 'heading',
        name: 'Spec 1 Title',
        parentId: 'estate_spec_1',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '🌊 Infinite Panoramic Views', level: 3 },
      },
      estate_spec_1_desc: {
        id: 'estate_spec_1_desc',
        type: 'text',
        name: 'Spec 1 description',
        parentId: 'estate_spec_1',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#475569' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Every single room is custom engineered with double-layered structural glass to present uninterrupted, breathtaking ocean horizons.</p>' },
      },
      estate_spec_2: {
        id: 'estate_spec_2',
        type: 'container',
        name: 'Spec Card 2',
        parentId: 'estate_grid_layout',
        children: ['estate_spec_2_title', 'estate_spec_2_desc'],
        layout: { backgroundColor: '#f1f5f9' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      estate_spec_2_title: {
        id: 'estate_spec_2_title',
        type: 'heading',
        name: 'Spec 2 Title',
        parentId: 'estate_spec_2',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '🛋️ Fully Integrated Smart Home', level: 3 },
      },
      estate_spec_2_desc: {
        id: 'estate_spec_2_desc',
        type: 'text',
        name: 'Spec 2 description',
        parentId: 'estate_spec_2',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#475569' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Control climates, entertainment consoles, security gates, and ambient lighting directly from your voice or connected phone.</p>' },
      }
    }
  }
};
