import { LandingPageTemplate } from '../templates';

export const restaurantTemplate: LandingPageTemplate = {
  templateId: 'restaurant_menu',
  name: 'Boutique Restaurant Food Funnel',
  description: 'High-conversions restaurant landing page with styled menus, table booking system, and secure order form.',
  category: 'RESTAURANT',
  schema: {
    version: '1.0.0',
    pageId: 'landing_page_demo_1',
    title: 'Restaurant Order',
    slug: 'gourmet',
    seo: {
      title: 'Verde Gourmet Salad Bar | Fresh Italian Bowls',
      description: 'Elite fresh italian bowls and organic salads delivered straight to your door in Chicago.',
      keywords: 'restaurant, gourmet, salad, delivery',
    },
    theme: {
      primaryColor: '#059669', // Fresh organic emerald
      secondaryColor: '#f59e0b',
      backgroundColor: '#ffffff',
      textColor: '#374151',
      fontHeading: 'Inter',
      fontBody: 'Inter',
    },
    rootBlockId: 'root_block',
    blocks: {
      root_block: {
        id: 'root_block',
        type: 'container',
        name: 'Restaurant Root',
        parentId: null,
        children: ['rest_section', 'rest_menu_section'],
        layout: { display: { desktop: 'block' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      rest_section: {
        id: 'rest_section',
        type: 'section',
        name: 'Rest Hero',
        parentId: 'root_block',
        children: ['rest_container'],
        layout: { backgroundColor: '#fffbeb' },
        spacing: { paddingTop: { desktop: '4rem' }, paddingBottom: { desktop: '4rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      rest_container: {
        id: 'rest_container',
        type: 'container',
        name: 'Rest Container',
        parentId: 'rest_section',
        children: ['rest_title', 'rest_cta_btn'],
        layout: {},
        spacing: { paddingLeft: { desktop: '1.5rem' }, paddingRight: { desktop: '1.5rem' } },
        typography: { textAlign: { desktop: 'center' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      rest_title: {
        id: 'rest_title',
        type: 'heading',
        name: 'Rest Title',
        parentId: 'rest_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '2rem' } },
        typography: { fontSize: { desktop: '2.5rem' }, fontWeight: { desktop: '800' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: 'Delivering Fresh Organic Salad Bowls and Italian Pastas', level: 1 },
      },
      rest_cta_btn: {
        id: 'rest_cta_btn',
        type: 'button',
        name: 'Rest Button',
        parentId: 'rest_container',
        children: [],
        layout: {},
        spacing: {},
        typography: {},
        border: { borderRadius: { desktop: '0.375rem' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: '⚡ Order Fast Delivery Now', variant: 'primary', action: { type: 'url', url: 'https://arena.ai' } },
      },
      rest_menu_section: {
        id: 'rest_menu_section',
        type: 'section',
        name: 'Menu Catalog',
        parentId: 'root_block',
        children: ['rest_menu_container'],
        layout: { backgroundColor: '#ffffff' },
        spacing: { paddingTop: { desktop: '4rem' }, paddingBottom: { desktop: '4rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      rest_menu_container: {
        id: 'rest_menu_container',
        type: 'container',
        name: 'Menu Wrapper',
        parentId: 'rest_menu_section',
        children: ['rest_menu_layout'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      rest_menu_layout: {
        id: 'rest_menu_layout',
        type: 'grid',
        name: 'Menu Columns Grid',
        parentId: 'rest_menu_container',
        children: ['rest_item_1', 'rest_item_2'],
        layout: { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: '1fr 1fr' }, gap: { desktop: '2rem' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      rest_item_1: {
        id: 'rest_item_1',
        type: 'container',
        name: 'Menu Card 1',
        parentId: 'rest_menu_layout',
        children: ['rest_item_1_title', 'rest_item_1_desc'],
        layout: { backgroundColor: '#fcfdfa' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' }, borderColor: '#f0fdf4', borderStyle: 'solid', borderWidth: { desktop: '1px' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      rest_item_1_title: {
        id: 'rest_item_1_title',
        type: 'heading',
        name: 'Card 1 Title',
        parentId: 'rest_item_1',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '🥗 Avocado Caesar Bowl - $12', level: 3 },
      },
      rest_item_1_desc: {
        id: 'rest_item_1_desc',
        type: 'text',
        name: 'Card 1 description',
        parentId: 'rest_item_1',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#475569' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Organic chopped romaine, grilled chicken breast, fresh sliced hass avocados, parmesan shavings, and homemade garlic dressing.</p>' },
      },
      rest_item_2: {
        id: 'rest_item_2',
        type: 'container',
        name: 'Menu Card 2',
        parentId: 'rest_menu_layout',
        children: ['rest_item_2_title', 'rest_item_2_desc'],
        layout: { backgroundColor: '#fcfdfa' },
        spacing: { paddingTop: { desktop: '2rem' }, paddingBottom: { desktop: '2rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.5rem' }, borderColor: '#f0fdf4', borderStyle: 'solid', borderWidth: { desktop: '1px' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      rest_item_2_title: {
        id: 'rest_item_2_title',
        type: 'heading',
        name: 'Card 2 Title',
        parentId: 'rest_item_2',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.5rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '🍝 Truffle Mushroom Penne - $16', level: 3 },
      },
      rest_item_2_desc: {
        id: 'rest_item_2_desc',
        type: 'text',
        name: 'Card 2 description',
        parentId: 'rest_item_2',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#475569' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Al dente penne pasta tossed in premium black truffle oil cream, loaded with wild porcini, swiss brown, and fresh parsley.</p>' },
      }
    }
  }
};
