import { LandingPageTemplate } from '../templates';

export const saasLanderTemplate: LandingPageTemplate = {
  templateId: 'saas_lander',
  name: 'SaaS Alpha Premium Dark Lander',
  description: 'An ultra-premium, high-converting dark-theme landing page with glowing gradient headers, micro-animations, and full conversion hierarchy.',
  category: 'SAAS',
  schema: {
    version: '1.0.0',
    pageId: 'landing_page_demo_1',
    title: 'SaaS Alpha Home',
    slug: 'home',
    seo: {
      title: 'The Future of No-Code SaaS Engines | Alpha',
      description: 'Compile your visual layouts into lightweight, raw static files distributed globally on the Edge in sub-10ms response times.',
      keywords: 'saas, premium, compilation, speed, dark mode',
    },
    theme: {
      primaryColor: '#6366f1',
      secondaryColor: '#f43f5e',
      backgroundColor: '#090d16',
      textColor: '#f1f5f9',
      fontHeading: 'Inter',
      fontBody: 'Inter',
    },
    rootBlockId: 'root_block',
    blocks: {
      root_block: {
        id: 'root_block',
        type: 'container',
        name: 'Root Layout Wrapper',
        parentId: null,
        children: ['hero_section', 'features_grid_section'],
        layout: { display: { desktop: 'block' }, width: { desktop: '100%' }, backgroundColor: '#090d16' },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      hero_section: {
        id: 'hero_section',
        type: 'section',
        name: 'Hero Premium Section',
        parentId: 'root_block',
        children: ['hero_container'],
        layout: { backgroundColor: '#0a0f1d' },
        spacing: { paddingTop: { desktop: '8rem', mobile: '4rem' }, paddingBottom: { desktop: '6rem', mobile: '3rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      hero_container: {
        id: 'hero_container',
        type: 'container',
        name: 'Hero Center Wrapper',
        parentId: 'hero_section',
        children: ['hero_heading', 'hero_paragraph', 'hero_cta_btn'],
        layout: { display: { desktop: 'flex' }, flexDirection: { desktop: 'column' }, alignItems: { desktop: 'center' } },
        spacing: {},
        typography: { textAlign: { desktop: 'center' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      hero_heading: {
        id: 'hero_heading',
        type: 'heading',
        name: 'Hero Title',
        parentId: 'hero_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '1.5rem' } },
        typography: { fontSize: { desktop: '4rem', mobile: '2.5rem' }, fontWeight: { desktop: '900' }, color: '#ffffff' },
        border: {},
        shadow: {},
        animation: { type: 'slide-up', duration: 800 },
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: 'Create Instant, High-Converting Pages on the Edge', level: 1 },
      },
      hero_paragraph: {
        id: 'hero_paragraph',
        type: 'text',
        name: 'Hero Subtext Copy',
        parentId: 'hero_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '2.5rem' } },
        typography: { fontSize: { desktop: '1.25rem', mobile: '1.1rem' }, color: '#94a3b8' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Eliminate slow, bloated loaders. Compile your visual layouts into lightweight raw static files distributed globally in milliseconds.</p>' },
      },
      hero_cta_btn: {
        id: 'hero_cta_btn',
        type: 'button',
        name: 'Hero Glowing CTA',
        parentId: 'hero_container',
        children: [],
        layout: { backgroundColor: '#4f46e5' },
        spacing: { paddingTop: { desktop: '1rem' }, paddingBottom: { desktop: '1rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: { color: '#ffffff', fontSize: { desktop: '1.125rem' }, fontWeight: { desktop: '700' } },
        border: { borderRadius: { desktop: '0.5rem' } },
        shadow: { boxShadow: '0 10px 15px -3px rgba(79, 70, 229, 0.4)' },
        animation: { type: 'pulse', duration: 2000, infinite: true },
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { label: 'Start Scaling Free', variant: 'primary', action: { type: 'url', url: 'https://arena.ai' } },
      },
      features_grid_section: {
        id: 'features_grid_section',
        type: 'section',
        name: 'Features Grid Section',
        parentId: 'root_block',
        children: ['features_container'],
        layout: { backgroundColor: '#090d16' },
        spacing: { paddingTop: { desktop: '6rem' }, paddingBottom: { desktop: '6rem' } },
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      features_container: {
        id: 'features_container',
        type: 'container',
        name: 'Features Inner Box',
        parentId: 'features_grid_section',
        children: ['features_title', 'features_grid'],
        layout: {},
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      features_title: {
        id: 'features_title',
        type: 'heading',
        name: 'Section Subheading',
        parentId: 'features_container',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '4rem' } },
        typography: { fontSize: { desktop: '2.5rem' }, fontWeight: { desktop: '800' }, textAlign: { desktop: 'center' }, color: '#ffffff' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: 'Engineered for Performance Marketers', level: 2 },
      },
      features_grid: {
        id: 'features_grid',
        type: 'grid',
        name: '3-Column Features Grid Layout',
        parentId: 'features_container',
        children: ['feat_1'],
        layout: { display: { desktop: 'grid', mobile: 'block' }, gridTemplateColumns: { desktop: 'repeat(3, minmax(0, 1fr))' }, gap: { desktop: '2rem' } },
        spacing: {},
        typography: {},
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      feat_1: {
        id: 'feat_1',
        type: 'container',
        name: 'Feature Card 1',
        parentId: 'features_grid',
        children: ['feat_1_title', 'feat_1_text'],
        layout: { backgroundColor: 'rgba(255,255,255,0.02)' },
        spacing: { paddingTop: { desktop: '2.5rem' }, paddingBottom: { desktop: '2.5rem' }, paddingLeft: { desktop: '2rem' }, paddingRight: { desktop: '2rem' } },
        typography: {},
        border: { borderRadius: { desktop: '0.75rem' }, borderColor: 'rgba(255,255,255,0.05)', borderStyle: 'solid', borderWidth: { desktop: '1px' } },
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: {},
      },
      feat_1_title: {
        id: 'feat_1_title',
        type: 'heading',
        name: 'Feature 1 Title',
        parentId: 'feat_1',
        children: [],
        layout: {},
        spacing: { marginBottom: { desktop: '0.75rem' } },
        typography: { fontSize: { desktop: '1.25rem' }, fontWeight: { desktop: '700' }, color: '#ffffff' },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { text: '⚡ Sub-10ms Compile', level: 3 },
      },
      feat_1_text: {
        id: 'feat_1_text',
        type: 'text',
        name: 'Feature 1 Copy',
        parentId: 'feat_1',
        children: [],
        layout: {},
        spacing: {},
        typography: { color: '#94a3b8', lineHeight: { desktop: '1.6' } },
        border: {},
        shadow: {},
        animation: {},
        visibility: { showOnDesktop: true, showOnTablet: true, showOnMobile: true },
        props: { htmlContent: '<p>Our Edge native compiler pipes HTML stream directly to visitors, bypassing database queries.</p>' },
      }
    }
  }
};
